### ISSUE TITLE
Set a default startupProbe, that would wait for Traefik to be really ready

### ISSUE THREAD

**Issue by mossroy** [traefik/traefik-helm-chart#1000]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

#951 allows to set a startupProbe, but there is no default one, for now.

When Traefik is starting, it is currently considered "ready" even if all the routes are not configured (because the readinessProbe and livenessProbe check /ping, that answers HTTP 200 very early)
So incoming HTTP requests can receive some HTTP 404, or the TLS certificate of another route, for the few seconds until all routes are setup.
This happens on startup but also for any change that requires a "rollout restart" of traefik pod (for example any configuration change or update of this helm chart)

The idea would be to add a default startupProbe in the bundled values.yaml, that would check somehow that the initial setup of Traefik is complete.
It would still allow users of the Helm chart to override this startupProbe with their own custom one if they need.

I had suggested that for k3s (https://github.com/k3s-io/k3s/issues/9475), but they answered it would be better to ask for it here.

**Comment by mloiseleur** [comment]
Hello @mossroy,

Thanks for your intereset in Traefik.

A known workaround to this issue is to set `initialDelaySeconds` on readiness.  

TBH, I have no idea how to 
> check somehow that the initial setup of Traefik is complete.

If you have an idea, feel free to open a PR.

**Comment by mossroy** [comment]
For now, I've manually added this :
```
    startupProbe:
      exec:
        command:
          - sh
          - "-c"
          - "wget -q --spider -O - http://127.0.0.1:9000/api/http/routers/myrouter@kubernetes"
        failureThreshold: 10
```
targeted to the most important router (i.e. kube ingress rule) I have in my k3s cluster.
It's far from perfect, but is a working first step in my case.

My apologies that I don't know Traefik internals. Maybe there would be a similar URL that would return an HTTP 200 only when all configured routers are available?

**Comment by mossroy** [comment]
https://github.com/kanopy-platform/traefik-startup-probe seems to try to solve the same issue with a side-car container checking if the number of providers is stable, to say if Traefik is ready or not. I'm not sure if it's a reliable way to do it.

**Comment by mloiseleur** [comment]
Checking availability of a router can work, yes. 

I have submitted an issue upstream, on traefik proxy.
https://github.com/traefik/traefik/issues/10458

I'll close this issue, since there is nothing to do on the Helm Chart FTM.
Feel free to re-open it if you see something that can be done on this topic.

**Comment by mossroy** [comment]
Great, many thanks for the ticket you created
