### ISSUE TITLE
Annotation with null value causes ArgoCD permanent out of sync

### ISSUE THREAD

**Issue by andrzejpawcenis** [traefik/traefik-helm-chart#1019]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v26.1.0

### What version of Traefik are you using?

v2.11.0

### What did you do?

I'm deploying traefic controller on kubernetes cluster by ArgoCD, but due to ```annotations: null``` in `traefik/templates/dashboard-ingressroute.yaml` argo stuck on out of sync status, because chart differs than live resource on cluster (null values are not presented on resources)
![Zrzut ekranu z 2024-03-15 14-41-02](https://github.com/traefik/traefik-helm-chart/assets/147497315/f78cf3bd-86aa-4f06-9d80-78f992769d96)

### What did you see instead?

My application on ArgoCD stucks in out of sync status due to this null annotation.

### What is your environment & configuration?

its irrevelant, because on fresh cluster without any specific configuration effect will be the same.

**Comment by mloiseleur** [comment]
Hello @andrzejpawcenis,

Thanks for your interest in Traefik Proxy. It's valid and works on Kubernetes to have an empty `metadata.annotations` so it seems more an issue on ArgoCD than on this Chart.
Anyway, feel free to submit a PR if you need it.

**Comment by andrzejpawcenis** [comment]
Hello @mloiseleur 

sure, i have prepared fix for this, how could i get an access to pushing a branch and create the PR?

**Comment by mloiseleur** [comment]
@andrzejpawcenis It's a public repo.You can fork it, create a branch on this fork and, when it's a ready, submit a PR on this upstream repo.

**Comment by andrzejpawcenis** [comment]
oh in that way. thank you very much for explanation. i will back with PR

**Comment by mloiseleur** [comment]
Fixed with #1021
