### ISSUE TITLE
Enable passthrough

### ISSUE THREAD

**Issue by mamu-reply** [traefik/traefik-helm-chart#1023]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi, It would be really useful to be able to enable passthrough as indicated here
[https://doc.traefik.io/traefik/routing/routers/#passthrough](https://doc.traefik.io/traefik/routing/routers/#passthrough)
but from the helm seem to be not possible.
Thanks

**Comment by mloiseleur** [comment]
Hello @mamu-reply ,

Thanks for reaching out!

TCP routers is a dynamic configuration that has been implemented through [IngressRouteTCP](https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroutetcp) CRD.

To keep the repository focused on the Chart, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly.
