### ISSUE TITLE
No obvious option in chart to set encodeQuerySemicolons

### ISSUE THREAD

**Issue by broomfn** [traefik/traefik-helm-chart#1050]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

27.0.2

### What version of Traefik are you using?

v2.11.2

### What did you do?

I want/need to be able to set encodeQuerySemicolons via he helm chart.

See https://github.com/traefik/traefik/issues/9164 and https://doc.traefik.io/traefik/routing/entrypoints/#encodequerysemicolons for more details.

### What did you see instead?

I couldn't see how to set it, unless I've missed something 🤷 

### What is your environment & configuration?

I need to deploy traefix to Kubernetes (hence the use of helm charts) and I need to encodeQuerySemicolons to support OData which used semicolons in query strings.

**Comment by mloiseleur** [comment]
Hello @broomfn,

Thanks for your interest in Traefik.
There is value in this Chart named `additionalArguments`.

For taking the doc example of Traefik CLI for _encodequerysemicolons_, it means that using a values like this:

```yaml
additionalArguments:
  - "--entryPoints.websecure.http.encodequerysemicolons=true"
```

will generate the expected argument on pod. You can check yaml generated with `helm template` command.

Does that answer your question ?

BTW, If you need it on a regular basis, feel free to open a PR.

**Comment by broomfn** [comment]
Thanks, I'll use that 👍
