### ISSUE TITLE
serverstransporttcps.traefik.io not being created by the Helm chart on upgrade to 28.0.0?

### ISSUE THREAD

**Issue by johanneskastl** [traefik/traefik-helm-chart#1061]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

traefik-28.0.0

### What version of Traefik are you using?

v3.0.0

### What did you do?

- Upgrade the 2.x Traefik installation with `helm upgrade ... -f values.yaml`.
- Checked the list of Traefik CRDs
- Applied the CRDs manually

### What did you see instead?

Apparently the `` CRD was not created by the chart upgrade. In the `kubectl apply` step it is being shown as `created`, not `configured`:

```
$ kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v3.0/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
Warning: resource customresourcedefinitions/ingressroutes.traefik.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/ingressroutes.traefik.io configured
Warning: resource customresourcedefinitions/ingressroutetcps.traefik.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/ingressroutetcps.traefik.io configured
Warning: resource customresourcedefinitions/ingressrouteudps.traefik.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/ingressrouteudps.traefik.io configured
Warning: resource customresourcedefinitions/middlewares.traefik.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/middlewares.traefik.io configured
Warning: resource customresourcedefinitions/middlewaretcps.traefik.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/middlewaretcps.traefik.io configured
Warning: resource customresourcedefinitions/serverstransports.traefik.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/serverstransports.traefik.io configured
customresourcedefinition.apiextensions.k8s.io/serverstransporttcps.traefik.io created
Warning: resource customresourcedefinitions/tlsoptions.traefik.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/tlsoptions.traefik.io configured
Warning: resource customresourcedefinitions/tlsstores.traefik.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/tlsstores.traefik.io configured
Warning: resource customresourcedefinitions/traefikservices.traefik.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/traefikservices.traefik.io configured

```

### What is your environment & configuration?

k3s clusters with Traefik installed via the helm chart, not using the one included in k3s.

**Comment by johanneskastl** [comment]
Uninstalling and re-installing Traefk seems to properly create the CRDs.

```
$ helm install traefik traefik/traefik -n traefik-system -f Traefik/values.yaml 
NAME: traefik
LAST DEPLOYED: Sun May  5 18:49:30 2024
NAMESPACE: traefik-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Traefik Proxy v3.0.0 has been deployed successfully on traefik-system namespace !
$ k get crds|grep traefik
ingressroutes.traefik.io                        2024-05-05T16:49:28Z
ingressroutetcps.traefik.io                     2024-05-05T16:49:28Z
ingressrouteudps.traefik.io                     2024-05-05T16:49:29Z
middlewares.traefik.io                          2024-05-05T16:49:29Z
middlewaretcps.traefik.io                       2024-05-05T16:49:29Z
serverstransports.traefik.io                    2024-05-05T16:49:29Z
serverstransporttcps.traefik.io                 2024-05-05T16:49:29Z
tlsoptions.traefik.io                           2024-05-05T16:49:29Z
tlsstores.traefik.io                            2024-05-05T16:49:29Z
traefikservices.traefik.io                      2024-05-05T16:49:29Z

```

**Comment by mloiseleur** [comment]
It's an expected behavior, documented [here](https://github.com/traefik/traefik-helm-chart?tab=readme-ov-file#upgrading-crds).
AFAIK, there is nothing we can do on this Chart.
Feel free to open a PR if you see something that can be done.

**Comment by johanneskastl** [comment]
Hi @mloiseleur, thanks for the fast reply.

Sorry, I do not agree with your analysis, I am not talking about updating the CRDs. I know handling existing CRDs are icky with helm.

But: The new traefik.io CRDs **were** installed during the upgrade. But not all of them. On of them was missing for some reason.

And that should be fixable, right?

**Comment by mloiseleur** [comment]
The CRDs in `traefik.io` are installed since [v23](https://github.com/traefik/traefik-helm-chart/releases/tag/v23.0.0) of this Chart (and Traefik v2.10).

If you know a way to improve the situation, a PR is more than welcome !

**Comment by johanneskastl** [comment]
Another cluster, running on traefik-27.0.2, is also missing the servertransporttcps, in both the old and the new version (`traefik.io` and `containo.us`:

```
ingressroutes.traefik.containo.us            2022-02-15T10:25:18Z
ingressroutes.traefik.io                     2023-07-10T06:40:05Z
ingressroutetcps.traefik.containo.us         2022-02-15T10:25:18Z
ingressroutetcps.traefik.io                  2023-07-10T06:40:06Z
ingressrouteudps.traefik.containo.us         2022-02-15T10:25:18Z
ingressrouteudps.traefik.io                  2023-07-10T06:40:06Z
middlewares.traefik.containo.us              2022-02-15T10:25:19Z
middlewares.traefik.io                       2023-07-10T06:40:06Z
middlewaretcps.traefik.containo.us           2022-02-15T10:25:19Z
middlewaretcps.traefik.io                    2023-07-10T06:40:06Z
serverstransports.traefik.containo.us        2022-02-15T10:25:19Z
serverstransports.traefik.io                 2023-07-10T06:40:06Z
tlsoptions.traefik.containo.us               2022-02-15T10:25:19Z
tlsoptions.traefik.io                        2023-07-10T06:40:06Z
tlsstores.traefik.containo.us                2022-02-15T10:25:19Z
tlsstores.traefik.io                         2023-07-10T06:40:06Z
traefikservices.traefik.containo.us          2022-02-15T10:25:20Z
traefikservices.traefik.io                   2023-07-10T06:40:07Z
```

**Comment by johanneskastl** [comment]
https://github.com/traefik/traefik-helm-chart/tree/master/traefik/crds

This looks like the servertransporttcps CRD was only added some months ago. So this cluster might not have gotten them, as the others were already created 2023-07 according to the previous comment.

**Comment by mloiseleur** [comment]
> Another cluster, running on traefik-27.0.2, is also missing the servertransporttcps, in both the old and the new version (`traefik.io` and `containo.us`:

That is expected behavior. `serverstransporttcps` CRD comes with Traefik Proxy v3.

**Comment by johanneskastl** [comment]
I tested on two other clusters, on both I had to manually install the serverstransporttcps CRD after the helm upgrade. All other CRDs were already installed in July 2023 like in the output above.

**Comment by johanneskastl** [comment]
There are not CRD-related options in the chart's values.yaml, other than the `kubernetesCRD` provider.

So I have no clue if I need to use a different command on upgrade than what I currently use

```
helm upgrade traefik traefik/traefik -n traefik-system -f Traefik/values.yaml
```

I personally think this is a bug somewhere in Helm or the chart.

I'll try to provide a reproducer.

**Comment by mloiseleur** [comment]
It seems upgrading section is not clear enough.

Would you please review this PR  ?

- https://github.com/traefik/traefik-helm-chart/pull/1062

**Comment by johanneskastl** [comment]
I can have a look later, but on first glance this does not cover the current issue. If the other CRDs could be installed fine by the chart, why could the servertransporttcps CRDs not be installed successfully?

Yes, forcefully applying the whole bunch of CRDs to the cluster solves this, but only by accident. Ideally, the chart should create it properly.

Or am I missing something?

**Comment by mloiseleur** [comment]
Yes, you are missing something: https://helm.sh/docs/chart_best_practices/custom_resource_definitions

**Comment by johanneskastl** [comment]
> Yes, maybe you are missing something: https://helm.sh/docs/chart_best_practices/custom_resource_definitions

What exactly are you referring to? Method 1 (`Let helm Do It For You`)  does not explain, why a single CRD could not be created by the chart.

Existing CRDs will be skipped. No deletion or upgrade possible. That is basically what your PR was about, right?

**Comment by johanneskastl** [comment]
And if my questions appear rude, they are not meant to be. I just would like to understand your line of arguments, hence my questions...

**Comment by mloiseleur** [comment]
It says explicitly:

> There is now a special directory called crds that you can create in your chart to hold your CRDs. These CRDs are not templated, but will be installed by default when running a helm install for the chart.

=> This Chart can install all required CRDs. 

*AND*

> There is no support at this time for upgrading or deleting CRDs using Helm. 

=> It can not install a new CRD during upgrade

**Comment by johanneskastl** [comment]
> > There is no support at this time for upgrading or deleting CRDs using Helm.
> 
> => It can not install a new CRD during upgrade

Thanks for taking the time to reply. I now understand what you mean.

I think the setup in this chart is as it should be, to me it looks like a bug in helm. Or bad wording.

Because in combination with the `If the CRD already exists, it will be skipped with a warning` I would assume that helm does **not** handle the whole `crd` directory as one thing. I would assume that for every file in there, the CRD will be created, **if it does not yet exist**. If it exists, there will be a warning, so no upgrading of existing CRDs.

Again, this might be bad wording on the helm side. If helm really applies the `crd` directory "as a whole", then you are right, adding another CRD on upgrading a chart is then not possible.
