### ISSUE TITLE
k3s v1.28/Rancher 2.8.3 : chart requires kubeVersion: >=1.22.0-0 which is incompatible with Kubernetes v1.20.0 

### ISSUE THREAD

**Issue by R-Nabil** [traefik/traefik-helm-chart#1066]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

28

### What version of Traefik are you using?

28

### What did you do?

Hi all, 

Upgraded my helm chart to 28 (i'm deploying using Fleet in Rancher). And i'm getting this error.
Is there anything i'm doing wrong ? It tells me version > 1.22 is required where my k3s is already 1.28

### What did you see instead?

chart requires kubeVersion: >=1.22.0-0 which is incompatible with Kubernetes v1.20.0 

### What is your environment & configuration?

k3s v1.28
Rancher 2.8.3
Fleet 0.9.4

**Comment by darkweaver87** [comment]
Hello @R-Nabil ,

I'm sorry to read you experience some troubles upgrading this chart.
Per this [PR](https://github.com/traefik/traefik-helm-chart/pull/1035/files#diff-ba22aa51b44ab3feb99c9b7cba4dfad404398576b6b7e64b6df8307d3c406304L8) the requirements have been updated.

Would you mind to share the output of the following command, your kube context pointing to the cluster you mention:

```
kubectl version
```

Thanks.

Rémi

**Comment by R-Nabil** [comment]
> Hello @R-Nabil ,
> 
> I'm sorry to read you experience some troubles upgrading this chart. Per this [PR](https://github.com/traefik/traefik-helm-chart/pull/1035/files#diff-ba22aa51b44ab3feb99c9b7cba4dfad404398576b6b7e64b6df8307d3c406304L8) the requirements have been updated.
> 
> Would you mind to share the output of the following command, your kube context pointing to the cluster you mention:
> 
> ```
> kubectl version
> ```
> 
> Thanks.
> 
> Rémi

Of course not. Thank you for taking the time to answer and help.

Is thit what you needed ?
```
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2+k3s1
WARNING: version difference between client (1.30) and server (1.28) exceeds the supported minor version skew of +/-1
```

**Comment by darkweaver87** [comment]
Hum, that's weird indeed :-/
Which version of helm (`helm version`) are you using ? We will try to reproduce and fix it ...
Thanks !

**Comment by R-Nabil** [comment]
Its actually done through Rancher Fleet (0.9.4) directly.

**Comment by R-Nabil** [comment]
Hi.

This issue can be closed. The error message was a red-herring. The issue was actually due to a middleware I use.
Once that was corrected, all flew through correctly.

Again appreciate your time in trying to help!

**Comment by darkweaver87** [comment]
OK I'm happy you solved. I'm sorry I set up a fleet environment this morning but I didn't have the chance to test :-)

**Comment by R-Nabil** [comment]
The fact you tried is honestly greatly appreciated

Thanks again
