### ISSUE TITLE
ECS provider don't work with IRSA on EKS Fargate - listing tasks: NoCredentialProviders

### ISSUE THREAD

**Issue by erihanse** [traefik/traefik-helm-chart#1091]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

traefik-26.1.0

### What version of Traefik are you using?

v2.11.0

### What did you do?

We're trying to integrate EKS with ECS, directing traffic from traefik running as a pod in EKS to an ECS service. 

We've set up IRSA, and we get this to work with a dummy pod, like explained [here](https://repost.aws/knowledge-center/eks-pods-iam-role-service-accounts), with the same service account we use for traefik.

I'm not sure yet if this is a configuration error or if traefik don't support such a scenario. Any ideas for how to troubleshoot this? It works when using node groups.

### What did you see instead?

We're seeing this in the logs of the traefik pod:
> [traefik-6996b4c446-9dbql] {"level":"error","msg":"Provider connection error failed to get ECS configuration: listing tasks: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors, retrying in 250.011391ms","providerName":"ecs","time":"2024-06-13T12:42:11Z"}

### What is your environment & configuration?

EKS, k8s v1.29

**Comment by mloiseleur** [comment]
Thanks for reaching out! To keep this repository focused on the Chart, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly.
