### ISSUE TITLE
Implement log.filePath

### ISSUE THREAD

**Issue by zchef2k** [traefik/traefik-helm-chart#1118]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

The ability to set log.filePath [per documentation](https://doc.traefik.io/traefik/observability/logs/#filepath).

Presently only log.format and log.level are implemented. [accesslog.*](https://github.com/traefik/traefik-helm-chart/blob/0153a52ea1edb169e2c33f2d7a95e57990d507b6/traefik/templates/_podtemplate.tpl#L630) is on par with documentation.

**Comment by darkweaver87** [comment]
Makes sense. Thanks for reporting this :-)

**Comment by mloiseleur** [comment]
It has been implemented in linked PR. 
Feel free to re-open this issue or create a new one if we missed something.
