### ISSUE TITLE
Traefik is using CNI gateway instead client IP

### ISSUE THREAD

**Issue by Qbason** [traefik/traefik-helm-chart#1149]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

30.0.1

### What version of Traefik are you using?

3.0

### What did you do?

I migrated from 27.0.2 to 30.0.1 using seperate fresh kubernetes microk8s environment.
I switched from IPWhiteList to IPAllowList as it was described in docs.

### What did you see instead?

All the time I got forbidden response.
In logs I read that traefik sees that traffic is comming from IP: 10.1.54.1 which is invalid.
I looked up in my network list 
5: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether 22:1b:83:91:a0:e0 brd ff:ff:ff:ff:ff:ff
    inet 10.1.54.1/24 brd 10.1.54.255 scope global cni0
       valid_lft forever preferred_lft forever
      
Traefik sees CNI IP address?

### What is your environment & configuration?

YAML which where only the name was changed (to ipAllowList now)

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: local-network
spec:
    ipAllowList:
        sourceRange:
            - 127.0.0.1/32
            - 192.168.1.0/24
            - 172.25.16.0/24
            - 10.0.0.0/24
            
microk8s status ->
microk8s is running
addons:
  enabled:
    dns                  # (core) CoreDNS
    helm                 # (core) Helm - the package manager for Kubernetes
    helm3                # (core) Helm 3 - the package manager for Kubernetes

**Comment by darkweaver87** [comment]
Hello @Qbason,

Which CNI are you using ? 
If you use flannel you might need to set `service.spec.externalTrafficPolicy: "Local"` (cf. https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip).

Rémi

**Comment by Qbason** [comment]
Hi @darkweaver87 
Firstly thank you for really quick response
I applied the service.spec.externalTrafficPolicy as you said.
Now I see that everything works :) 
Do you have any thoughts why before it was working ?
I am 100% sure that I didn't apply externalTrafficPolicy via values before (I was looking for last changes).

**Comment by darkweaver87** [comment]
Hello @Qbason,

Well I don't know ...
If you're sure that the service loadBalancer externalTrafficPolicy was not set, may be you were using a different CNI (e.g. calico) or a NodePort?
