### ISSUE TITLE
Disabling dashboard ingressroute does not delete it

### ISSUE THREAD

**Issue by sshishov** [traefik/traefik-helm-chart#115]
If during initial setup you go with default settings then dashboard ingressroute is created. If you disable it afterwards and apply, ingressroute is still present and accessible.
I assume, if you disable dashboard, this ingress route should be deleted, even `diff` is showing that it will be deleted.
I suspect that actual problem is that the this route is created as hook.

**Comment by dtomcej** [comment]
@sshishov you are correct.

Because the ingressRoute is created as a hook, helm does not manage the created object.

If you want to disable the dashboard after having it enabled, you will have to manually delete the ingressRoute object.

**Comment by Nittarab** [comment]
Hi, maybe I do something wrong.  
I would not delete the dashboard. But I would be able to upgrade the chart, for example to improve the static configuration.

When I try to upgrade I get this error:
```
UPGRADE FAILED
Error: ingressroutes.traefik.containo.us "traefik-dashboard" already exists
Error: UPGRADE FAILED: ingressroutes.traefik.containo.us "traefik-dashboard" already exists
```
I'm using this commands to upgrade:
```
kubectl delete ingressroutes traefik-dashboard -n traefik
helm upgrade -f values.yaml traefik traefik/traefik
```

**Comment by arenstar** [comment]
Having the same problem as @Nittarab

**Comment by Nittarab** [comment]
I didn't find any solution at the moment..

**Comment by jakubhajek** [comment]
Hello @Nittarab @arenstar 

I've installed Traefik and than added a few changes to the `values.yaml `and then successfully upgraded Traefik - no issue experienced with the `ingressroutes/traefik-dashboard` rule. 

Would you please try the same with the latest version of the Helm Chart ? Thank you,
