### ISSUE TITLE
Add support for defining the static configuration via helm chart

### ISSUE THREAD

**Issue by ilmax** [traefik/traefik-helm-chart#1155]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

As per the title, it would be nice to be able to support the static configuration in the values file of the helm chart, without having to resort to the args and cli syntax, like it's done [here](https://github.com/traefik/traefik/blob/bd93e224deb434b4cd8ffe5c85e52c8b0f54f57a/integration/fixtures/k8s-conformance/02-traefik.yml#L46-L55)

**Comment by mloiseleur** [comment]
Hello @ilmax ,

Thanks for your interest in Traefik. 
The link provided shows using CLI args: 
![image](https://github.com/user-attachments/assets/39920050-d843-4836-bb1e-264746495717)

Would you please detail what you have in mind ?

**Comment by ilmax** [comment]
Hello @mloiseleur, my idea was to make the static configuration a first class citizen of the helm chart to a) make it more discoverable and b) allow configuring it via yml instead of using the cli arguments.

This issue has been created because I wasn't sure where to put the following code
```yml
kubernetesGateway:
   statusAddress:
     service:
       name: traefik
       namespace: traefik
```
I thought it was just a part of the helm chart value file but after the apply nothing changed. It some time to understand a) what's the static configuration and b) how to set it using the helm chart.

This issue aims to make it more discoverable, so people who approach traefik for the fist time will not repeat my mistakes. (I was playing around with the Gateway support)

Another option could be to have something more explicit in the documentation that a) states what's the static configuration and b) explains/shows how to set it via helm.

Let me know if this make sense to you

**Comment by mloiseleur** [comment]
This chart provides [examples](https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md) for newcomers.
Wdyt about adding a new example with your use case ?

If you think we can improve the README of this Chart, then would you please open a PR ?

In a more global way, we have started to align yaml configuration format in _values_ of this Chart with yaml configuration format in Traefik. It cannot be done in one step, so we are doing it one step at a time. 

For configuration, it's managed by upstream (traefik) project. The [current documentation](https://doc.traefik.io/traefik/getting-started/configuration-overview/) has been improved multiple times.

**Comment by ilmax** [comment]
Hey @mloiseleur interesting, I didn't see the chart example, I was mostly looking at the documentation and the chart values.yml and inside the templates folder. For example I totally missed the configuration documentation that you linked above so I was wondering if you think adding backreferences from the pages that refers to static configuration (or any other type of configuration) could possibly helm. 

I for example was on this [page](https://doc.traefik.io/traefik/providers/kubernetes-gateway/) trying to get traefik to expose the address of the traefik service and It's not immediately clear where to add this configuration, a backreference to the configuration may be useful here.

I can try to come up with a PR for either readme or the examples if you want me to

**Comment by mloiseleur** [comment]
> I can try to come up with a PR for either readme or the examples if you want me to

Sure.

**Comment by mloiseleur** [comment]
I'll close this issue.

Feel free to open a PR when you have a time.
