### ISSUE TITLE
Issue with gateway.networking.k8s.io CRDs in combination with GKE

### ISSUE THREAD

**Issue by menzbua** [traefik/traefik-helm-chart#1183]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

31.0.0

### What version of Traefik are you using?

3.1.2

### What did you do?

Hi,

When I deploy the latest Helm-Chart with the new gateway-standard-install-v1.1.0.yaml CRDs I have a conflict with already deployed gateway.networking.k8s.io CRDs on our GKE Cluster. The Problem is, that you prefer the v1 APIs and the GKE Cluster prefers the v1beta1 APIs.

Here is an excerpt of the CRD from the gatewayclasses CRD comes with a fresh installed GKE Cluster:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.kubernetes.io: https://github.com/kubernetes-sigs/gateway-api/pull/2997
    components.gke.io/component-name: gateway-api-crds
    components.gke.io/component-version: 1.1.0-gke.0
    components.gke.io/layer: addon
    gateway.networking.k8s.io/bundle-version: v1.1.0
    gateway.networking.k8s.io/channel: standard
  creationTimestamp: "2024-09-13T09:19:46Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: gatewayclasses.gateway.networking.k8s.io
  resourceVersion: "703"
  uid: 40b9ef55-269c-4e60-a846-5a00d5586e8c
spec:
  conversion:
    strategy: None
  group: gateway.networking.k8s.io
  names:
    categories:
    - gateway-api
    kind: GatewayClass
    listKind: GatewayClassList
    plural: gatewayclasses
    shortNames:
    - gc
    singular: gatewayclass
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.controllerName
      name: Controller
      type: string
    - jsonPath: .status.conditions[?(@.type=="Accepted")].status
      name: Accepted
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .spec.description
      name: Description
      priority: 1
      type: string
    name: v1
    schema:
      ...
    served: true
    **storage: false**
    subresources:
      status: {}
  - additionalPrinterColumns:
    - jsonPath: .spec.controllerName
      name: Controller
      type: string
    - jsonPath: .status.conditions[?(@.type=="Accepted")].status
      name: Accepted
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .spec.description
      name: Description
      priority: 1
      type: string
    name: v1beta1
    schema:
      ...
    served: true
    **storage: true**
    subresources:
      status: {}
...
```
This configuration difference in the property "storage" leads to out-of-sync problems in ArgoCD. This issue matches all CRDs within the group gateway.networking.k8s.io. I think you well-considered why you chose v1 of the API. I just wanted to draw your attention to the fact that there is an issue with GKE Clusters and the latest Chart.

If anyone has a hint to avoid the ArgoCD sync-error without an ignoreDifferences config, please let me know.

### What did you see instead?

There is a configuration mismatch between the GKEs default CRDs and the Helm-Charts CRDs.

### What is your environment & configuration?

See problem description

**Comment by menzbua** [comment]
The issue is with GKE not EKS. GKE also uses the gateway API to talk to the Google Load balancers, I think.

**Comment by mloiseleur** [comment]
The Load Balancer is connected with an other mechanism. 

According to their documentation, it can be disabled: 

![image](https://github.com/user-attachments/assets/2a76d9c9-6e3f-4afd-b15f-4c1daa395305)

Their documentation says they are using v1beta1 and Traefik Proxy v3.1 is compatible with v1.1

**Comment by mloiseleur** [comment]
If I understand correctly your setup, you have two different Gateway controllers installed: 

1. GKE one, using v1beta1 standard CRDs
2. Traefik Proxy, using v1.1 standard CRDs

You may encounter other issues in this kind of setup. One way to fix it is to choose only one Gateway controller, and so with only one version of CRDs.

**Comment by mloiseleur** [comment]
\o, according to [gateway api website](https://gateway-api.sigs.k8s.io/implementations/#google-kubernetes-engine), GKE controller claim they support nearly everything of v1.1

**Comment by mloiseleur** [comment]
Without any answer, I close this issue. I do not see anything to do on the Chart.
Feel free to-reopen it (or open a new one) if needed.

**Comment by PurseChicken** [comment]
I also ran into this and posted here:

https://github.com/traefik/traefik-helm-chart/issues/1209#issuecomment-2447795030

There may be use cases where you have a combination of Traefik installed handling ingress and using gateway-api resources in GKE so you have it enabled there. In my case, I use a combination of ingress (traefik) and multi-cluster ingress (mci is tied to GKE gateway-api).

I am of the opinion that unless you want to enable traefik's gateway-api provider, then the CRD's should be optional. Maybe consider tying this to kubernetesGateway.enabled in values or something similar. Otherwise, at least in GKE, CRD conflicts are inevitable post v28.3.0 of the helm chart.
