### ISSUE TITLE
Add support for configuring `kubernetes.ingressEndpoint`

### ISSUE THREAD

**Issue by jannislehmann** [traefik/traefik-helm-chart#1229]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hey,

I'm using ArgoCD and deploy a few applications with using the native Kubernetes ingress.
Due to a bug or limitation in ArgoCD those applications are never shown as properly set up because ArgoCD expects the ingress to contain an updated `status.loadBalancer` value.

I've found this issue https://github.com/argoproj/argo-cd/issues/968/#issuecomment-451082913, which essentially describes that fixing this requires setting the `ingressEndpoint` in Traefik. However, it seems that this Helm chart does not allow configuring this field.
Would it be possible to add support for that? Or is there a different way that could be used to set the `kubernetes.ingressEndpoint`?

Further reading:
* https://github.com/argoproj/argo-cd/issues/4863
* https://github.com/argoproj/argo-cd/issues/4863#issuecomment-1400786602

**Comment by mloiseleur** [comment]
Is this related to [this PR](https://github.com/traefik/traefik-helm-chart/pull/1220) we merged last week ?

**Comment by jannislehmann** [comment]
Yes, this is exactly what I was looking for. I must have searched for the wrong key words.
Thanks!
