### ISSUE TITLE
Adding tracing sampleRate to chart values

### ISSUE THREAD

**Issue by slayne** [traefik/traefik-helm-chart#1269]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I wanted to activate sampling on tracing but did not find the option in the chart values.

I already opened a PR for this [here](https://github.com/traefik/traefik-helm-chart/pull/1268)

**Comment by mloiseleur** [comment]
Fixed with #1271
