### ISSUE TITLE
Maintain Changelog

### ISSUE THREAD

**Issue by Vad1mo** [traefik/traefik-helm-chart#175]
A changelog would allow everyone to keep track of what changes from version to verison. 

It doesn't have to be fancy just file the tracks the chages thats it.
here a good example: https://github.com/nginxinc/kubernetes-ingress/blob/master/CHANGELOG.md

**Comment by DanielHabenicht** [comment]
Apart from the keep-track-of changes aspect at the moment, I can't see at first glance which version the chart currently has and which traefik version it ships. (except going to the command line)

**Comment by ldez** [comment]
Fixed by ba98e364cf82d3c0d179b321aa668d53dc10e030

We now create a tag for each version.
