### ISSUE TITLE
Migration guide

### ISSUE THREAD

**Issue by Diaoul** [traefik/traefik-helm-chart#183]
I'm having trouble replacing a k3s setup with traefik v1 by this v2. I've tried plain and simple in-place substitution of the v1 chart by this one and couldn't get it to work.
Everything is running but I have a 404 when I hit traefik on a valid Ingress. I know my ingress is loaded because the SSL certificate is the one in the Ingress.
I've read the documentation and issues extensively and couldn't find the reason for this. I've tried many options and tweaking the values.yaml.
The only thing that is different is that my ingress doesn't seem to get an ADDRESS in the `kubectl get ingress` whereas it has one with v1.

I'm running metallb on brand new k3s without traefik, maybe this is related?
Is there a step I am missing? Maybe it's something wrong with my setup?
I think a migration guide would've helped me through this or at least help me know where to look, so I'm submitting the idea.

**Comment by delamart** [comment]
Hi I had the same or similar problem. If you want the TLS section in Ingress to be treated correctly in Traefik 2.2 you need to add the argument "--entryPoints.websecure.http.tls=true" in `additionalArguments`.
See https://docs.traefik.io/v2.2/migration/v2/#kubernetes-ingress

@SantoDE Maybe this should be done by default in the helm chart ? So Ingress works as expected (tls) out of the box.

**Comment by SantoDE** [comment]
Hey,

yeah, we should do that. We've raised a couple of "todo" issues to improve the helm chart, as well. I guess, it will fit nicely in there :)
