### ISSUE TITLE
Implement methods for simple use cases

### ISSUE THREAD

**Issue by SantoDE** [traefik/traefik-helm-chart#185]
Currently, the helm chart is very flexible and can be seen as a scaffolding base for further configuration and or enhancements by our users.

However, we will try to implement simple wrappers inside that helm chart for the following simple use cases:

- [Expose our dashboard publicly (with basic authentication)](https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#publish-and-protect-traefik-dashboard-with-basic-auth)
- ~~Provide a "default" Certificate for TLS~~
- ~~Redirect from HTTP to HTTPS globally~~
- ~~Set a log Level~~
- ~~Setup Lets Encrypt (ACME) with either HTTP or TLS challenge~~

This will not be a replacement for the current flexibility but rather an addition to it, to ease the installation process for the use-cases mentioned above.

**Comment by mloiseleur** [comment]
@SantoDE I guess we're good now. 
Please let me know if you think we missed something.
