### ISSUE TITLE
Setup Lets Encrypt (ACME) with either HTTP or TLS challenge

### ISSUE THREAD

**Issue by SantoDE** [traefik/traefik-helm-chart#190]
We want to implement a configuration option in the helm chart, to automatically start Traefik with a certResolver which either uses the HTTP or TLS challenge (and provide the needed configuration like email address)

Partially fixes #185

**Comment by armandleopold** [comment]
+1

**Comment by Letme** [comment]
I am very interested in this kind of enhancement. In v1 of the helm chart, there was a `ssl:` section where you would define your certResolver stuff, but it is just plainly missing from the current version, so the only way I see it defining this is through `additionalArguments`, correct?

**Comment by SantoDE** [comment]
correc @Letme. And if you want to raise a PR to fix that, you're very welcome 👼

**Comment by Letme** [comment]
OK, I will first try to get it working (so far ports 80 and 443 on kubernetes master node are not opened) as this is my first touch with Kubernetes (and Helm). I assume it could be stolen from v1 chart as there should not be much of a difference (at least simple settings).

**Comment by mloiseleur** [comment]
@SantoDE Do you think it's fixed with #285 ? Or is there something missing ?
