### ISSUE TITLE
Pod disruption budget should allow percentages

### ISSUE THREAD

**Issue by hintofbasil** [traefik/traefik-helm-chart#258]
A pod disruption budget should allow percentages for the `.spec.minAvailable` and `.spec.maxUnavailable` fields.
https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget

The chart casts them to integers which disallows this.
https://github.com/containous/traefik-helm-chart/blob/289d2b2/traefik/templates/poddisruptionbudget.yaml#L17

**Comment by LudovicTOURMAN** [comment]
We used to face a downtime of our production because of this conversion which lead to change `50%` to `0`.
Thanks for opening this issue guys, I created a corresponding PR to fix it.

**Comment by mloiseleur** [comment]
Fixed with #528
