### ISSUE TITLE
service doesn't see original source IP of requests

### ISSUE THREAD

**Issue by fireba11** [traefik/traefik-helm-chart#262]
We had to add

  externalTrafficPolicy: Local

to the service definition for that ...

**Comment by SantoDE** [comment]
👋  Hey. Thanks for your interest.

And what do you want to tell us with that? :) This has some other drawbacks, so I'm not sure what to do with that request? :) If there is no objection, I'd like to close that ticket.

**Comment by fireba11** [comment]
It seemed like a no-brainer to me.
But i'm willing to learn, what would be a reason not to set that?

**Comment by SantoDE** [comment]
`externalTrafficPolicy` is an opinionated configuration, which does not work in vanilla k8s out of the box. As you can see here (https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/), it requires some further support by either a cloud provider (if you're running on one) or a k8s environment which does support that feature in general. Also, local instructs k8s to only proxy the request to the service on a local endpoint, rather to a cluster-wide endpoint which can lead to not correctly balanced traffic.

Therefore, to me, its an option you should set willingly, rather to have it by default in the chart.

For that, I'll close that issue :-)
