### ISSUE TITLE
IngressClass not working on AWS EKS 1.18 Cluster - no matches for kind "IngressClass" in version "networking.k8s.io/v1"

### ISSUE THREAD

**Issue by r3kzi** [traefik/traefik-helm-chart#287]
The way this Helm chart tries to evaluate the API version for `IngressClass` doesn't work for AWS EKS 1.18 cluster.

``` 
  {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
  {{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
``` 

You will get...
``` 
error: unable to recognize "ingressclass.yaml": no matches for kind "IngressClass" in version "networking.k8s.io/v1"
``` 

...because `IngressClass` runs with `networking.k8s.io/v1beta1`.

```
$ k explain IngressClass                              
KIND:     IngressClass
VERSION:  networking.k8s.io/v1beta1
```

Because `NetworkPolicy` runs with `networking.k8s.io/v1` as an API version `.Capabilities.APIVersions.Has "networking.k8s.io/v1"` will IMHO evaluate to `true`.

```
$ for kind in `kubectl api-resources | tail +2 | awk '{ print $1 }'`; do kubectl explain $kind; done | grep -e "KIND:" -e "VERSION:"
...
KIND:     IngressClass
VERSION:  networking.k8s.io/v1beta1
KIND:     Ingress
VERSION:  extensions/v1beta1
KIND:     NetworkPolicy
VERSION:  networking.k8s.io/v1
```

**Comment by tobylo** [comment]
Just ran into this issue as well when upgrading to latest chart version. 
Cluster version 1.18.9.

**Comment by tobylo** [comment]
According to the docs @ https://helm.sh/docs/chart_template_guide/builtin_objects/

_Capabilities.APIVersions.Has $version indicates whether a version (e.g., batch/v1) **or resource (e.g., apps/v1/Deployment)** is available on the cluster._

If I'm reading that correctly, that should mean the template could be changed to:

`  {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass" }}
apiVersion: networking.k8s.io/v1
  {{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/IngressClass" }}
apiVersion: networking.k8s.io/v1beta1`

Will try it out.
