### ISSUE TITLE
It seems like additionalArguments doesn't work properly

### ISSUE THREAD

**Issue by vovkanaz** [traefik/traefik-helm-chart#293]
Hi there. We are trying to  add additional args to the traefik deployment according to:

 Add volumes to the traefik pod. The volume name will be passed to tpl.
 This can be used to mount a cert pair or a configmap that holds a config.toml file.
 After the volume has been mounted, add the configs into traefik by using the `additionalArguments` list below, eg:
```
 additionalArguments:
 - "--providers.file.filename=/config/dynamic.toml"
```

```
additionalArguments:
  - --providers.file.filename=/config/dynamic.toml
  - --providers.consulcatalog=true
  - --providers.consulcatalog.refreshInterval=30s
  - --providers.consulcatalog.prefix=traefik
  - --providers.consulcatalog.endpoint.address=consul-server.namespace.svc.cluster.local:8500
  - --providers.consulcatalog.endpoint.scheme=http
  - --providers.consulcatalog.endpoint.datacenter=dc
  - --providers.consulcatalog.endpoint.endpointwaittime=15s
  - --providers.consulcatalog.endpoint.httpauth.username=login
  - --providers.consulcatalog.endpoint.httpauth.password="pass"
```

After that, we have run helm upgrade --install...
but nothing changed...
So we decided to execute `kubectl edit deploy traefik `
and we have noticed that there are no new arguments inside `ARGS:` section, so we have decided to add it manually, and finally, everything begins to working well.
So it seems like additionalArguments: section, unfortunately, doesn't work.
Thanks in advance.

**Comment by vovkanaz** [comment]
And another question. Would you mind to help us to understand how to route traffic from Traefik Ingress to a ConsulCatalog Services which has been received from  Consul service discovery? Thanks.

**Comment by SantoDE** [comment]
Usually that section works. I did run it a couple of times already. Did you specify the location of the values file while running `help upgrade`?

**Comment by vovkanaz** [comment]
@SantoDE Sure, helm upgrade --install... -f values.yaml.
We have successfully figure out a problem with the help of GlobalArguments

**Comment by brianmori** [comment]
HI @vovkanaz,

I need also to supply a dynamic toml for TLS certificates and other configuration

 - "--providers.file.filename=/config/dynamic.toml"

Is my understanding correct the ConfigMap must be created outside the Helm Chart and only referenced by it ?

**Comment by SantoDE** [comment]
Yes, that is correct @brianmori

**Comment by jakubhajek** [comment]
> And another question. Would you mind to help us to understand how to route traffic from Traefik Ingress to a ConsulCatalog Services which has been received from Consul service discovery? Thanks.

Hello @vovkanaz, Regarding that kind of question I highly recommend using our [community forum](https://community.traefik.io/)

**Comment by mloiseleur** [comment]
In current versions of this Chart, update of `additionalArguments` seems to work. 
It's more an Helm 3 feature than a feature specific to this chart.
