### ISSUE TITLE
service annotation

### ISSUE THREAD

**Issue by jcputter** [traefik/traefik-helm-chart#295]
i'm trying to install traefik via helm using 

`helm install traefik  --namespace traefik stable/traefik --set service.annotations."kubernetes\.io\/elb\.autocreate=true"`

which fails with

`Error: services "traefik" is forbidden: unrecognized ingress elb autoCreate annotations`

any ideas? Thanks

**Comment by jcputter** [comment]
I see that chart is from the default helm repo, i tried to set service annotation using the traefik/traefik repo but not having much luck

**Comment by jakubhajek** [comment]
Hello @jcputter 

Thanks for using Traefik :)

Can you please try to using the following command: 

```
helm install  --set-string  service.annotations.'kubernetes\.io/elb\.autocreate'=true  traefik traefik/traefik
```

The following annotations should be added
```
Annotations:              kubernetes.io/elb.autocreate: true
                          meta.helm.sh/release-name: traefik
                          meta.helm.sh/release-namespace: default
```

**Comment by kevinpollet** [comment]
Hello @jcputter,

As there is no feedback for a long time we will close this issue accordingly.
If there is something new, feel free to re-open it or join our [Community Forum](https://community.traefik.io/).

Thanks for your interest in Traefik!
