### ISSUE TITLE
No data in dashboard

### ISSUE THREAD

**Issue by karthick-kk** [traefik/traefik-helm-chart#297]
I get a dashboard with blank data on all pages and tabs. Strangely traefik version on top right refers 1.7 although the image version is 2.3.1. Tried adding --api-insecure=true and it makes no difference. 

![image-20201030215008632](https://raw.githubusercontent.com/corestackdev/images/main/image-20201030215008632.png)

**Comment by jakubhajek** [comment]
Hello @karthick-kk 
Would you please try to deploy Traefik using the latest version? If you still experience the same issue please provide a minimum replicable scenario and we will investigate it. 

Thank you,

**Comment by kevinpollet** [comment]
Hello @karthick-kk,

As there is no feedback for a long time we will close this issue accordingly.
If there is something new, feel free to re-open it or join our [Community Forum](https://community.traefik.io/).

Thanks for your interest in Traefik!
