### ISSUE TITLE
404 not found - Dashboard error

### ISSUE THREAD

**Issue by Yalafeg** [traefik/traefik-helm-chart#301]
Hello,

I am trying to install traefik on my kubernetes cluster, but I am getting 404 error not found. I am not able to browse the dashboard even internally within the cluster.

Server version: v1.19.2
Client version: v1.16.7

Traefik version: 2.3.1

I followed the steps mentioned with no luck. Please can you advise if there is any configuration that should be modified from my side. 

In addition, I need to deactivate the SSL redirection.

Thank you for your help.

**Comment by Yalafeg** [comment]
kindly find below the debug logs of the traefik pod installed

time="--T08:34:39Z" level=info msg="Configuration loaded from flags."
time="--T08:34:39Z" level=info msg="Traefik version 2.3.1 built on 2020-09-29T15:49:06Z"
time="--T08:34:39Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true,\"sendAnonymousUsage\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"traefik\":{\"address\":\":9000/tcp\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"web\":{\"address\":\":8000/tcp\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}},\"websecure\":{\"address\":\":8443/tcp\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"idleTimeout\":180000000000}},\"forwardedHeaders\":{},\"http\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"kubernetesIngress\":{\"ingressClass\":\"traefik-internal\",\"ingressEndpoint\":{\"publishedService\":\"traefikservice/traefik\"}},\"kubernetesCRD\":{}},\"api\":{\"dashboard\":true},\"ping\":{\"entryPoint\":\"traefik\",\"terminatingStatusCode\":503},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"accessLog\":{\"format\":\"common\",\"filters\":{},\"fields\":{\"defaultMode\":\"keep\",\"headers\":{\"defaultMode\":\"drop\"}}}}"
time="--T08:34:39Z" level=info msg="Stats collection is enabled."
time="--T08:34:39Z" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
time="--T08:34:39Z" level=info msg="Help us improve Traefik by leaving this feature on :)"
time="--T08:34:39Z" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
time="--T08:34:39Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="--T08:34:39Z" level=debug msg="Start TCP Server" entryPointName=traefik
time="--T08:34:39Z" level=debug msg="Start TCP Server" entryPointName=websecure
time="--T08:34:39Z" level=debug msg="Start TCP Server" entryPointName=web
time="--T08:34:39Z" level=info msg="Starting provider *traefik.Provider {}"
time="--T08:34:39Z" level=info msg="Starting provider *ingress.Provider {\"ingressClass\":\"traefik-internal\",\"ingressEndpoint\":{\"publishedService\":\"traefikservice/traefik\"}}"
time="--T08:34:39Z" level=debug msg="Using Ingress label selector: \"\"" providerName=kubernetes
time="--T08:34:39Z" level=info msg="ingress label selector is: \"\"" providerName=kubernetes
time="--T08:34:39Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetes
time="--T08:34:39Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"ping\":{\"entryPoints\":[\"traefik\"],\"service\":\"ping@internal\",\"rule\":\"PathPrefix(`/ping`)\",\"priority\":2147483647}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{},\"ping\":{}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="--T08:34:39Z" level=info msg="Starting provider *crd.Provider {}"
time="--T08:34:39Z" level=debug msg="Using label selector: \"\"" providerName=kubernetescrd
time="--T08:34:39Z" level=info msg="label selector is: \"\"" providerName=kubernetescrd
time="--T08:34:39Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetescrd
time="--T08:34:39Z" level=debug msg="Added outgoing tracing middleware ping@internal" routerName=ping@internal middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik
time="--T08:34:39Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareType=Recovery middlewareName=traefik-internal-recovery
time="--T08:34:39Z" level=debug msg="No default certificate, generating one"
time="--T08:34:40Z" level=debug msg="Configuration received from provider kubernetescrd: {\"http\":{\"routers\":{\"default-traefik-dashboard-d012b7f875133eeab4e5\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/dashboard`) || PathPrefix(`/api`)\"},\"traefikservice-traefik-dashboard-d012b7f875133eeab4e5\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/dashboard`) || PathPrefix(`/api`)\"}}},\"tcp\":{},\"udp\":{},\"tls\":{}}" providerName=kubernetescrd
time="--T08:34:40Z" level=debug msg="Configuration received from provider kubernetes: {\"http\":{},\"tcp\":{}}" providerName=kubernetes
time="--T08:34:40Z" level=debug msg="Added outgoing tracing middleware ping@internal" routerName=ping@internal entryPointName=traefik middlewareName=tracing middlewareType=TracingForwarder
time="--T08:34:40Z" level=debug msg="Added outgoing tracing middleware api@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=default-traefik-dashboard-d012b7f875133eeab4e5@kubernetescrd
time="--T08:34:40Z" level=debug msg="Added outgoing tracing middleware api@internal" entryPointName=traefik routerName=traefikservice-traefik-dashboard-d012b7f875133eeab4e5@kubernetescrd middlewareName=tracing middlewareType=TracingForwarder
time="--T08:34:40Z" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=traefik middlewareName=traefik-internal-recovery
time="--T08:34:40Z" level=debug msg="No default certificate, generating one"
time="--T08:34:40Z" level=debug msg="Added outgoing tracing middleware api@internal" routerName=default-traefik-dashboard-d012b7f875133eeab4e5@kubernetescrd middlewareType=TracingForwarder middlewareName=tracing entryPointName=traefik
time="--T08:34:40Z" level=debug msg="Added outgoing tracing middleware api@internal" middlewareType=TracingForwarder middlewareName=tracing entryPointName=traefik routerName=traefikservice-traefik-dashboard-d012b7f875133eeab4e5@kubernetescrd
time="--T08:34:40Z" level=debug msg="Added outgoing tracing middleware ping@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=ping@internal
time="--T08:34:40Z" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
time="--T08:34:40Z" level=debug msg="No default certificate, generating one"

**Comment by Yalafeg** [comment]
Please can you advise if I missed a specific configuration?

**Comment by jnbptstm** [comment]
Resolved here : https://github.com/traefik/traefik-helm-chart/issues/320 ?

**Comment by jakubhajek** [comment]
hello @Yalafeg 

The default deployment enables Traefik dashboard and API. You can create port forwarding by 

`kubectl port-forward $(kubectl get pods --selector "app.kubernetes.io/name=traefik" --output=name) 9000:9000`

and then access the dashboard using `http://localhost:9000/dashboard/` - (please mind the trailing slash) - and API through `http://localhost:9000/api/version`

Can you please try it using the latest version?  

Thank you,
