### ISSUE TITLE
PVC implementation

### ISSUE THREAD

**Issue by mtompkins** [traefik/traefik-helm-chart#308]
Thank you for your work on the traefik chart.

The choice is bifurcating the PVC volumes into two sections seems quite counterintuitive. Specifically, you have a section of **persistence** and a subsequent part of the chart that allows **volumes**. 

I think some consideration should be given to a consolidated and proper ability to add volumes in the latter section, including the user's choice of multiple PVCs if desired. I do not see a seamless was to do this at this time. For example, a user may want to store the *acme.json* as well as persist logs on a host in a separate location.

If I'm incorrect in the chart templates ability to parse multiple preexisting PVCs, I welcome correction.

**Comment by mloiseleur** [comment]
Hello @mtompkins,

Thanks for your issue. 
With current version of the Helm Chart, one can use either `volumes` or `additionalVolume` + `additionalVolumeMounts`.

Does it work for you ?
