### ISSUE TITLE
Last Chart releases are not available in helm repo

### ISSUE THREAD

**Issue by Issif** [traefik/traefik-helm-chart#314]
Hi,

The last release of traefik Chart makes available custom labels for deployment, but we saw that it's not available in repository. The present one is `9.1.11` but the Chart we need is `9.11.0`. How do you manage that updates? When the `9.11.0` will be available from repository?

Thanks

**Comment by SantoDE** [comment]
Hello @Issif,

Which repository do you mean? The old one?

**Comment by Issif** [comment]
This one : https://containous.github.io/traefik-helm-chart

**Comment by SantoDE** [comment]
Yeah that is the old helm-chart, prior to our rebrand. We wont publish new releases to that chart anymore

**Comment by Issif** [comment]
👍 

For people who may ask same : https://artifacthub.io/packages/helm/traefik/traefik
