### ISSUE TITLE
Configmap and secret mount unusable

### ISSUE THREAD

**Issue by dza89** [traefik/traefik-helm-chart#315]
I'm trying to load my cert from a secret (because traefik can't write it to a secret itself, so much for proper stateless) but I can't, because I run into the wide permissions problems.
I can't run the busybox init container however, because a loaded secret is readonly by default and this is not editable.

What now? :)

**Comment by notsureifkevin** [comment]
Greetings, thank you for using the Traefik project. I believe your issue might be a question, and we typically direct our users to the forums (https://community.traefik.io) for questions pertaining to the use of Traefik and related projects.

Before you open a thread there though, I believe you may be able to resolve this issue by specifying the octal permissions on the secret object itself. Please see https://kubernetes.io/docs/concepts/configuration/secret/#secret-files-permissions for more information. If you continue to run into issues, please open a thread on the forums with additional information so the community can help you there.

_kc
