### ISSUE TITLE
Fail to access dashboard

### ISSUE THREAD

**Issue by Yalafeg** [traefik/traefik-helm-chart#320]
Hello,

I am deploying traefik helm chart on a kubernetes cluster, I am replacing the LoadBalancer service by ClusterIP or NodePort, then doing the port forward as recommended, but I am getting a 404 error while trying to access the /dashboard or /api pages, the same error appears even if I access the dashbord locally.

I tried to create the deployment, service and Ingressroutes seperately and I got the same error. I tried also to add the additional argument "--api.insecure" and I got the same error.

Please can you advise what might be the issue? Am I doing an error during the configuration and installation process? Kindly note that the only modification that I made is on the level of the server by changing the LoadBalancer type.  Can you guide me please during the troubleshooting process? Am I missing something?

Thanks.

**Comment by jnbptstm** [comment]
Hello @Yalafeg ,

Did you try with a trailing slash / at the end of your URL ? <my-dashboard>/dashboard **/**
Without this slash, Traefik also gives me `404 page not found`

If it is still not working, can you provide logs of your Traefik pod ?

**Comment by Yalafeg** [comment]
Hello, thank you for your reply, it is working now.
