### ISSUE TITLE
ingressclass template causes chart install to fail when using non-semver values in `image.tag`

### ISSUE THREAD

**Issue by kevtainer** [traefik/traefik-helm-chart#321]
I encountered this issue when trying to force the helm chart to use the `latest` image tag when testing a new feature. This bug cannot be worked around because the logic is always going to evaluate the SemVer in the following code (even if `.Values.ingressClass.enabled` evaluates to `false`):

https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/ingressclass.yaml#L1

Do we need this logic check here? Is it not enough to assume the operator is enabling `ingressClass` when they understand their cluster has the required APIs and support? See related issue - https://github.com/traefik/traefik-helm-chart/issues/309

values.yaml:

```yaml
        image:
          name: traefik/traefik
          tag: latest
          pullPolicy: Never

```

Result:

```
can't install chart `traefik`: template: traefik/templates/ingressclass.yaml:1:41: executing \"traefik/templates/ingressclass.yaml\" at <semverCompare \">=2.3.0\" (default .Chart.AppVersion .Values.image.tag)>: error calling semverCompare: Invalid Semantic Version"
```

**Comment by ldez** [comment]
Friends don't let friends get friends use `latest`.

You will never be able to be sure of the real version.

If you really want to take the risk, use `v2` instead of `latest`.

I think `v2` is semver compliant.
