### ISSUE TITLE
Optionally run traefik as a daemonset

### ISSUE THREAD

**Issue by igaskin** [traefik/traefik-helm-chart#322]
Previous versions of traefik documentation refer to runing traefik as a deployment or a daemonset.  The helm chart should support either configuration. 
https://doc.traefik.io/traefik/v1.7/user-guide/kubernetes/#deploy-traefik-using-a-deployment-or-daemonset

*Use Case*
Users that run dedicated node pools for ingress controllers can use a daemonset to scale to each node in that pool.

**Comment by notsureifkevin** [comment]
fixed by https://github.com/traefik/traefik-helm-chart/pull/298

**Comment by igaskin** [comment]
Closed as resolved.
