### ISSUE TITLE
[BUG] Helm Chart's templates do not use the tolerations except in the Deployment yaml

### ISSUE THREAD

**Issue by dmusicant-dk** [traefik/traefik-helm-chart#323]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I created a cluster with tainted server nodes:
```bash
k3d cluster create dev --api-port 6551 --port "8081:80@loadbalancer" --servers 3 --k3s-server-arg --node-taint="CriticalAddonsOnly=true:NoExecute" --k3s-server-arg "--no-deploy=traefik"
```
Then I tried to install Traefik from the Helm chart **with added tolerations**
```bash
helm install traefik traefik/traefik --set tolerations[0].key=CriticalAddonsOnly --set tolerations[0].operator=Exists --set tolerations[0].effect=NoExecute
```
When I try to reach the dashboard, I get a 404.
```bash
kubectl port-forward $(kubectl get pods --selector "app.kubernetes.io/name=traefik" --output=name) 9000:9000

# I then went to http://127.0.0.1:9000/dashboard/
```

### What did you expect to see?

The dashboard

### What did you see instead?

A 404 Not Found message.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.3.6
```

### The Workaround

I was able to get it to work by:

1. Uninstalling Traefik `helm uninstall traefik`
2. Creating non-tainted worker nodes `k3d node create worker --cluster dev --replicas 3`
3. Reinstalling traefik

Then I was able to reach the dashboard. But I should have been able to add tolerations to everything Traefik installs.

**Comment by darkweaver87** [comment]
Hello @dmusicant-dk,

Sorry for late answer :-)

I'm not able to reproduce your issue with the current helm template and traefik versions.

```bash
k3d cluster create --k3s-arg '--no-deploy=traefik@servers:*' --k3s-arg '--node-taint=CriticalAddonsOnly=true:NoExecute@all:*' --image="rancher/k3s:v1.23.13-k3s1"


helm repo add traefik https://helm.traefik.io/traefik
helm repo update
helm install traefik traefik/traefik --set tolerations[0].key=CriticalAddonsOnly --set tolerations[0].operator=Exists --set tolerations[0].effect=NoExecute

kubectl port-forward $(kubectl get pods --selector "app.kubernetes.io/name=traefik" --output=name | head -n 1) 9000:9000
```

It works:
```bash
$ curl -XGET http://127.0.0.1:9000/dashboard/ -I
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 3124
Content-Security-Policy: frame-src 'self' https://traefik.io https://*.traefik.io;
Content-Type: text/html; charset=utf-8
Date: Wed, 09 Nov 2022 14:21:47 GMT
```

and tolerations are correctly set:

```bash
$ kubectl get deployments.apps traefik -o jsonpath='{.spec.template.spec.tolerations}'
[{"effect":"NoExecute","key":"CriticalAddonsOnly","operator":"Exists"}]
```

Same thing with daemonset deployment kind:

```bash
$ kubectl get daemonsets.apps traefik -o jsonpath='{.spec.template.spec.tolerations}'
[{"effect":"NoExecute","key":"CriticalAddonsOnly","operator":"Exists"}]
```

Feel free to reopen the issue if needed.

Rémi
