### ISSUE TITLE
Unable to install traefik with chart v9.12.1

### ISSUE THREAD

**Issue by anthosz** [traefik/traefik-helm-chart#329]
Hello,

Since, the upgrade it's not possible to install from scratch traefik via HELM:
- Impacted version: 9.12.1
- Works with: 9.11.0

Error:
`Error: failed to install CRD crds/ingressroute.yaml: CustomResourceDefinition.apiextensions.k8s.io "ingressroutes.traefik.containo.us" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion(nil): must have exactly one version marked as storage version, status.storedVersions: Invalid value: []string(nil): must have at least one stored version]`

**Comment by dhirschfeld** [comment]
I'm seeing the same thing with 9.12.2:
```
+ version                    = "9.12.2"

module.helm.helm_release.traefik: Creating...

Error: failed to install CRD crds/ingressroute.yaml: CustomResourceDefinition.apiextensions.k8s.io "ingressroutes.traefik.containo.us" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion(nil): must have exactly one version marked as storage version, status.storedVersions: Invalid value: []string(nil): must have at least one stored version]
```

**Comment by SantoDE** [comment]
Looking into it right now

**Comment by SantoDE** [comment]
Should be good again. Sorry folks, thats on me. I missed that :)

**Comment by dhirschfeld** [comment]
Thanks for the quick fix @SantoDE & happy new years from Brisbane, Australia - I hope you enjoy the rest of the day with no further worries! 🎆 🎉
