### ISSUE TITLE
Executing helm chart 9.12.1 against microk8s results in error

### ISSUE THREAD

**Issue by pvandervelde** [traefik/traefik-helm-chart#330]
I'm trying to install Traefik in a microk8s instance using the following commands

    helm repo add traefik https://helm.traefik.io/traefik
    helm repo update
    helm install -f ./traefik/config.yaml traefik traefik/traefik

Where the `config.yaml` file is a copy (with no alterations) of the traefik helm `values.yaml`. When executing this I get the following error.

    Error: failed to install CRD crds/ingressroute.yaml: CustomResourceDefinition.apiextensions.k8s.io
    "ingressroutes.traefik.containo.us" is invalid: [spec.versions: Invalid value:
    []apiextensions.CustomResourceDefinitionVersion(nil): must have exactly one version marked as
    storage version, status.storedVersions: Invalid value: []string(nil): must have at least one
    stored version]

When I use `--version 9.12.0` as an extra argument to Helm the deployment succeeds (although the kubernetes dashboard shows Traefik as `pending state`).

Note that I'm just starting to tinker with kubernetes and microk8s so I might well have done something wrong.

**Comment by anthosz** [comment]
duplicate #329
