### ISSUE TITLE
Helm chart : replicas and DNS acme resolver

### ISSUE THREAD

**Issue by Leopol35** [traefik/traefik-helm-chart#335]
Hello,

I am using Traefik 2.3.X in an "on premise" kubernetes cluster. I use GandiV5 DNS resolver to get certificates for traefik.

In the helm chart, you forbid to use an "acme" configuration when there is more than 1 pod replica.

```
{{- if and .Values.deployment.enabled (eq .Values.deployment.kind "Deployment") -}}
  {{- if gt (int .Values.deployment.replicas) 1 -}}
    {{- with .Values.additionalArguments -}}
      {{- range . -}}
        {{- if contains ".acme." . -}}
          {{- fail (printf "You can not enabled acme if you set more than one traefik replica") -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
```

I totally understand this for HTTP-01, TLS-SNI and TLS-ALPN challenge but for DNS-01, it should be ok to have more than one replica. In case of DNS challenge, Traefik will check the DNS entry to the provider, it(s not an incoming traffic to traefik.

Thanks for your help,

Kind regards,

**Comment by rdxmb** [comment]
According to [the closed pull request](https://github.com/traefik/traefik-helm-chart/pull/366) this issue could be closed, right?

(In my case, I use traefik 2.2 as a deployment with 2 replicas - event with HTTP-ACME. The acme.json is on NFS. This is working for about 130 days in 3 datacenters. Seems I've had just luck?)

**Comment by Leopol35** [comment]
Hello,

Yes, I close, thanks a lot for your attention. I was not aware of this limitation about let's encrypt certificate.

Kind regards,
