### ISSUE TITLE
Support for overriding the liveness/readiness probes port

### ISSUE THREAD

**Issue by ttauveron** [traefik/traefik-helm-chart#339]
Hello,

I spent a bit of time recently to deploy traefik behind a Google L7 HTTP/S Load balancer.
To create a HTTPS Load balancer in GKE, a service must first have a NodePort type and an Ingress of type "gce" must point to this service. Google will then automatically create healthchecks using by default the configuration specified in the pod for liveness/readiness probes. However, by default, this helm chart uses the "traefik" entrypoint port (that shouldn't be exposed) and the Google Load balancer cannot succeed its healthchecks because it can't reach this entrypoint. 

I managed to solve this by modifying the ping configuration in traefik : 

```yaml
additionalArguments:
  - "--ping"
  - "--ping.entrypoint=web"
```

and change the liveness/readiness ports to the web entrypoint one (by default, 8000 instead of 9000).

Would that make sense in this chart to support overriding those liveness/readiness ports in the values?

Something like that?

```diff
diff --git a/traefik/templates/_podtemplate.tpl b/traefik/templates/_podtemplate.tpl
index f401d26..3d5ddc5 100644
--- a/traefik/templates/_podtemplate.tpl
+++ b/traefik/templates/_podtemplate.tpl
@@ -38,7 +38,7 @@
         readinessProbe:
           httpGet:
             path: /ping
-            port: {{ .Values.ports.traefik.port }}
+            port: {{ default .Values.ports.traefik.port .Values.ports.traefik.healthchecksPort }}
           failureThreshold: 1
           initialDelaySeconds: 10
           periodSeconds: 10
@@ -47,7 +47,7 @@
         livenessProbe:
           httpGet:
             path: /ping
-            port: {{ .Values.ports.traefik.port }}
+            port: {{ default .Values.ports.traefik.port .Values.ports.traefik.healthchecksPort }}
           failureThreshold: 3
           initialDelaySeconds: 10
           periodSeconds: 10
diff --git a/traefik/values.yaml b/traefik/values.yaml
index 50cab94..8dfe19c 100644
--- a/traefik/values.yaml
+++ b/traefik/values.yaml
@@ -207,6 +207,11 @@ ports:
   # liveness probes, but you can adjust its config to your liking
   traefik:
     port: 9000
+
+    # Override the liveness/readiness port. This is useful to integrate traefik
+    # with an external Load Balancer that performs healthchecks.
+    # healthchecksPort: 9000
+
     # Use hostPort if set.
     # hostPort: 9000
     #
```

**Comment by gajus** [comment]
Others may find this article useful, which tackles related subject https://blog.ttauveron.com/posts/traefik_behind_google_l7_load_balancer/
