### ISSUE TITLE
Failed connect to traefik.localhost:80

### ISSUE THREAD

**Issue by JesseStutler** [traefik/traefik-helm-chart#348]
Hi, it's my first time using traefik. I followed the 'installing' part in README.md, But I can't access the dashboard. I used `curl http://traefik.localhost/dashboard/` to test, but I got `curl: (7) Failed connect to traefik.localhost:80`.Were there some steps I missed? I have doubts about the kind named traefikservice, I can't find this resource in any namespace or any service named api@internal...? If so, how does it works to access the dashboard? 
Surely I can access the dashboard by `kubectl port-forward $(kubectl get pods --selector "app.kubernetes.io/name=traefik" --output=name) 9000:9000`, but I want to use the host/path way to access outside the cluster. Thanks for any advice.

**Comment by av8ta** [comment]
I have the same problem :-1: :(

**Comment by JesseStutler** [comment]
I think it's because can't resolve traefik.localhost to any IP address. But as I said, can't find any service that has a relation to the dashboard...and then can't find the IP address to bond with traefik.localhost.

**Comment by faust64** [comment]
You just have to query whichever port your Traefik is listening on.
Using hostNetwork, that would be one of your nodes addresses. Maybe there's a LoadBalancer or a NodePort service that was created, ... Maybe there's no service at all, and container doesn't have hostNetwork: then, it's up to you to expose traefik.
As you did notice, the README mentions setting up some port-forward, which would connect to the container directly.
Also, your IngressRoute should match a FQDN that actually points to Traefik (`traefik-dashboard.apps.example.com`, with apps.example.com a dns wildcard resolving to your kubernetes ingress nodes or some external LB).

**Comment by JesseStutler** [comment]
I changed my ingress controller scheme, close it now, thanks.
