### ISSUE TITLE
Helm Chart and apiextensions.k8s.io/v1beta1 ?

### ISSUE THREAD

**Issue by dbalsige** [traefik/traefik-helm-chart#350]
Hi there

I get some warnings about deprecated apiextensions.k8s.io/v1beta1 when installing the helm chart. 
The warnings show up with either 2.4.x (chart version 9.14.0) or 2.3.x (chart version 9.12.3) 

`helm install --namespace=traefik --create-namespace --version ${traefik_chart_version}  traefik traefik/traefik -f traefik-values.yaml`
`W0202 15:55:06.553003     928 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

+15 times the same message.

Though I have apiextensions.k8s.io/v1 available:
`kubectl api-versions | grep apiextensions`
`apiextensions.k8s.io/v1`
`apiextensions.k8s.io/v1beta1`

K8s version:  v1.19.7 
Helm version: v3.5.0+g32c2223

Anybody knows what is going wrong ?
Any help is greatly appreciated.

**Comment by SantoDE** [comment]
Hey 👋 

We are aware of that and this will be gone once we released 2.5. It is linked to https://github.com/traefik/traefik/pull/7815.

As this is a question, Ill close that issue.

**Comment by dbalsige** [comment]
Thank you for the fast reply and the explanation, I was not able to add the kind/question label to the issue, when opening it.
