### ISSUE TITLE
How to setup HSTS header middleware?

### ISSUE THREAD

**Issue by runlevel5** [traefik/traefik-helm-chart#381]
As title, from my understanding there is config to enable this middleware:

```
[http.middlewares]
  [http.middlewares.testHeader.headers]
    frameDeny = true
    sslRedirect = true
```

however I don't see any option in `values.yaml` to configure that.

Any guidance is greatly appreciated. I am also happy to cook up new PR to provide the missing features if the core team is okay

### References

* https://doc.traefik.io/traefik/middlewares/headers/#using-security-headers

**Comment by SantoDE** [comment]
That needs to be done in your dynamic configuration :) Best is to create a Middleware CR with that configuration. https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-middleware.

That you can then reference.

As this is primarily a question, Ill close that issue. If you have more questions, feel free to reach out on our community forum 👍
