### ISSUE TITLE
deployment is stuck but doesn't show a clear message what is wrong.

### ISSUE THREAD

**Issue by marcofranssen** [traefik/traefik-helm-chart#382]
**Chart versions:** `9.15.2`, `9.15.1`, `9.14.3`
**Traefik Version:** `2.4.6`, `2.4.5`
**Kubectl and k8s version:** `1.19.3`

I have tested with above versions. 2 days ago I was still able to deploy traefik using this chart with the default values, using chart version `9.15.1`.

Now the deployment somehow is stuck. Tested with both `9.15.2` and `9.15.1`.

This is all I can see in the logs of traefik.

```bash
2021-03-05 14:18:48 ERROR: command for release [traefik] returned [ 1 ] exit code and error message [ W0305 14:13:46.097844   95773 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0305 14:13:46.108286   95773 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0305 14:13:46.119342   95773 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0305 14:13:46.132822   95773 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0305 14:13:46.141593   95773 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0305 14:13:46.150883   95773 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0305 14:13:46.158212   95773 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0305 14:13:46.166494   95773 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

All resources show a green state in the kubernetes dashboard, except for the service which shows a gray icon.

I can't find the cause of this. I think before I also saw the warning, but then it successfully started.

**Comment by faust64** [comment]
Those CustomResourceDefinition warnings are quite common, nothing to worry about, until Kubernetes 1.22 .... Still, it doesn't explain why your command mentions some `command for release [traefik] returned [ 1 ] exit code ...`, while none of the following message actually mentions an error.

Can you clarify how is it stuck? 
Are you updating a previous deployment, or  creating a new one?
What command did you run exactly?

The service in gray might just mean that whichever Pod should serve as an endpoint is not ready yet.
Do you see Traefik Pods running? Maybe they're crashing? If so, have you checked their logs? -- `kubectl logs -n <traefik-namespace> <traefik-pod-name>`
If you don't see any Pod, you may want to check `kubectl get events -n <traefik-namespace>`. There may be a reason why the scheduler refuses to create it.

**Comment by marcofranssen** [comment]
I think it was related to another ingress controller on our cluster. We started from scratch and now it works. Not sure how to reproduce. I will close the ticket, in case it happens again, I will try to report back the root cause.
