### ISSUE TITLE
Add issue templates for clearer areas where to ask questions

### ISSUE THREAD

**Issue by jaydrogers** [traefik/traefik-helm-chart#383]
Hey Traefikers,

Thanks again for the maintenance and support of this project. As a new comer coming in with many questions, I had a mis-understanding on where to ask support questions.

After working with some others on this repo, it's my understanding that your preference is to have it on the Traefik forum (which is great!).

My incorrect assumption was the forum was for "general traefik" questions and this repo was for helm chart specific questions.

When I ask questions, **I definitely want to make it as easy and friction-less as possible for maintainers to answer a question**. 💯

### Proposal how to clear this up
I think adding issue templates would help drive a lot of users to the proper places. This will help make it easier for the maintainers to deal with less stress of organizing issues.

We ran into the same issue on our own open source project, but adding templates worked great:
<img width="1257" alt="Screen Shot 2021-03-05 at 8 50 09 AM" src="https://user-images.githubusercontent.com/3174134/110132578-ed9a3100-7d90-11eb-87c0-719f78a06693.png">

I have the code here between the two files if you want to copy it (or I can submit a PR if you'd like): https://github.com/serversideup/amplitudejs/tree/master/.github/ISSUE_TEMPLATE

Since you are using Discourse (we are too) there are a lot of cool things that you can do:
* Link to a post how to ask questions
* When they click "create question" it can auto tag it too

See this example: https://github.com/serversideup/amplitudejs/issues/new/choose

Implementing this for us has saved a lot of time and confusion. Quality of responses and focus has also improved for us.

Just some thoughts I would like to share. Any questions, let me know. Thanks for your hard work!

**Comment by kevinpollet** [comment]
Closed by https://github.com/traefik/traefik-helm-chart/pull/444
