### ISSUE TITLE
v2 Chart no longer exposes documentation about configuring tracing

### ISSUE THREAD

**Issue by abatilo** [traefik/traefik-helm-chart#394]
On the stable v1 chart, there was the ability to configure tracing to multiple backends right from the chart's values file:
https://github.com/helm/charts/blob/master/stable/traefik/values.yaml#L480

Could we get that same ability in the current chart and documentation?

**Comment by devpikachu** [comment]
Is there still no tracing support added?

**Comment by mloiseleur** [comment]
Hello,

Thanks for your interest in Traefik. Tracing support was added with this PR 
- #608 

Is there anything missing ?

**Comment by abatilo** [comment]
I think this can be closed!
