### ISSUE TITLE
Get proxy protocol working correctly

### ISSUE THREAD

**Issue by rjbaat** [traefik/traefik-helm-chart#404]
Hi All,
I am trying to get proxy protocol enabled on my Traefik setup on DigitalOcean k8s. 
The hw load balancer has proxy protocol. I can enable it manually, but then I get a error 400 respons from my ingressRoute.

I tried to add an additional argument to the entry point web with the trusted ip. I tried it with the internal subnet of DO and 127.0.0.1/32 like stated in the documentation. But on my 3 node cluster it sometimes gives the node ip of one of the 3 cluster nodes, instead of my ISP ip. I think this is because it is the node that Traefik container actual lives on.

```
--entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,<INTERNAL_IP_SUBNET>
```
I noticed that it only truly works when I add the additional argument like:

```
--entryPoints.web.proxyProtocol.insecure
```
Any idea how to get proxy protocol working with the DO load balancer entry points, without getting the node ip?

**Comment by tanandy** [comment]
hi, are you using externeltrafficpolicy to local ?

**Comment by rjbaat** [comment]
Hi, when I check the Traefik LB it stated: 

```
externalTrafficPolicy: Cluster
```

**Comment by tanandy** [comment]
ok sorry, you dont try to get the real source ip , do you ? or you just want proxy protocol enable

**Comment by rjbaat** [comment]
No I actually do want the see client ip and not the ip's in between. 
Aha i will test it with setting it to local then.

**Comment by tanandy** [comment]
could you describe the LB created to see if we have some annotation on your lb for the proxy protocol

**Comment by tanandy** [comment]
> Aha i will test it with setting it to local then.

ok then if you need also to retrieve the real ip, you will need to be in local at least

**Comment by tanandy** [comment]
for your information i put a working example here, you can get some insights with it on OVH and adapt it to DO

https://github.com/tanandy/helm-ovh-ingress

**Comment by tanandy** [comment]
https://docs.digitalocean.com/products/kubernetes/how-to/configure-load-balancers/#:~:text=Enabling%20the%20PROXY%20protocol%20allows,information%20from%20the%20load%20balancer.

service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true" in your value as i did for ovh

**Comment by rjbaat** [comment]
I tried to do the 
```
externalTrafficPolicy: Local
```

But then only 1 node is healthy on the hw load balancer. Because it will not forward traffic to the other nodes. So I don't think that is the solution. 

What I did was adding this to the helm chart as extra answers:
```
additionalArguments:
  - "--entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,10.133.0.0/16"
service:
  annotations: 
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
```

This is what I will test atm, to see if it solves it.

**Comment by rjbaat** [comment]
@tanandy thnx!
I think that this indeed solves it. I only see my own ip now. 
Stupid, since I had this annotation for NGINX before aswel 🙈.

**Comment by tanandy** [comment]
you have 2 different things : 

1/ you need to activate proxy protocol on ingress + lb (to support proxy protocol)

2/ you need to use externalTrafficPolicy local (to be able to retrieve real ip)

**Comment by rjbaat** [comment]
Number 2 isn't needed, since it then breaks the LB.
I guess that would only work if Traefik runs as a DaemonSet.

**Comment by tanandy** [comment]
really, i always needed to setup externaltrafficpolicy to local to get the real ip of the user. you may be lucky

**Comment by rjbaat** [comment]
Well if I do that, 2 of the 3 nodes in the LB pool will show unhealthy.

**Comment by tanandy** [comment]
interesting, im not using DO. it could be useful to understand the reason. Maybe the difference between OVH & DO lbs

**Comment by rjbaat** [comment]
Wel I think it might be due to the health checks. These are done on the node ports of the Traefik container on every node in the cluster. But if the health check doesn't reach the Traefik container (because of `externalTrafficPolicy: Local`) the the LB marks the node as unhealthy. 

Anyway, iam not sure what can be done. Strange thing is that the same concept is working for NGINX.

**Comment by tanandy** [comment]
https://docs.digitalocean.com/products/kubernetes/how-to/configure-load-balancers/#proxy-protocol

>External Traffic Policies and Health Checks
Load balancers managed by DOKS assess the health of the endpoints for the LoadBalancer service that provisioned them.

>A health check’s behavior is dependent on the service’s externaltrafficpolicy. A service’s externaltrafficpolicy can be set to either Local or Cluster. A Local policy only accepts health checks if the destination pod is running locally, while a Cluster policy allows the nodes to distribute requests to pods in other nodes within the cluster.

> Services with a Local policy assess nodes without any local endpoints for the service as unhealthy.

> Services with a Cluster policy can assess nodes as healthy even if they do not contain pods hosting that service. To change this setting for a service, run the following command with your desired policy:

>Note
If a service has a Cluster policy, requests will lose the original client IP address due to the extra network hop between the load balancer and the nodes. If your service requires retaining the requests original IP address, a Local policy is requires.

**Comment by tanandy** [comment]
you may need to customize healthcheck ?

```
metadata:
  name: health-check-snippet
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "5"
    ```

**Comment by tanandy** [comment]
you can mitigate the traffic spread using pod anti affinity btw, its not perfect but its not that bad

**Comment by rjbaat** [comment]
yes indeed, or it should be set to the kind DaemonSet maybe? But iam not sure if that's possible with this helm chart options.

**Comment by tanandy** [comment]
i dont see why using DaemonSet will resolve it ?

**Comment by rjbaat** [comment]
A DaemonSet ensures that all (or some) Nodes run a copy of a Pod. So it well make sure every node has at least one Traefik container if I am right about this. https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

So if every node has one Traefik pod and I set the `externalTrafficPolicy: Local` then the health checks on each node will work and the the routing from each Traefik pod should use the preserved ip.

**Comment by tanandy** [comment]
ok,i was talking about the fact of not using externaltrafficpolicy local but cluster. i dont know about the daemonset, you could test im only using defaut chart currently that works for me but im not on DO.

if you want to avoid using local and downside of this approach, you could mix proxy protocol + x forwarded for header (to preserve security)
https://devcentral.f5.com/s/articles/How-to-persist-real-IP-into-Kubernetes

**Comment by rjbaat** [comment]
@tanandy , how does that work, I don't think I quite understand. I tried to add the forwarded headers like adding: 

`--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,10.133.0.0/16` 

But it does not seam to work in combination with `externalTrafficPolicy: Cluster` .

The thing is that with the same setup and with DO loadbalancer + proxy protocol + NGINX it does work with: `externalTrafficPolicy: Cluster`

So NGINX uses the headers maybe differently then Traefik.

**Comment by tanandy** [comment]
i dont get your point . why are you trying to use forwarded headers ?

**Comment by rjbaat** [comment]
No I tried to add them both to see if it then will use the headers as client ip, but it doesn't matter.
I am still stuck in the fact it won't work without `externalTrafficPolicy: Local`. But that would break the DO lb health check. 

I was wondering why I do get it to work with NGINX on `externalTrafficPolicy: Cluster` with the following helm answers:

```
---
  controller: 
    config: 
      use-proxy-protocol: "true"
    service:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
```

**Comment by tanandy** [comment]
nginx + traefik support both forwarded headers + proxy protocol

**Comment by rjbaat** [comment]
Yes, but on NGINX I do get it to work with `externalTrafficPolicy: Cluster` and on Traefik I don't. 

Both have the DO LB annotation and Both have proxy protocol enabled.

**Comment by tanandy** [comment]
because you have to adapt traefik deployment to make DO hck works

**Comment by rjbaat** [comment]
Yes, but with the `externalTrafficPolicy: Cluster` option it would still be better since the routing of the request will run over the whole cluster. With the local option it only looks for Traefik container on the node the request will enter. So then I have to make sure Traefik runs on all nodes. 

Anyway thnx for your help! I will see if I can find a good solution.

**Comment by tanandy** [comment]
told you, you cant use externalTrafficPolicy: Cluster to get the real source ip afaik (for the reason above) 
if you want to use it and retrieve ip without local , you will probably need to follow Proxyprotocol + forwarded header (for sec reason)  with the architecture above.

**Comment by rjbaat** [comment]
Yes, I read the article, but didn't quite understand the proposed solution.

**Comment by tanandy** [comment]
the first mw will handle the proxy protocol part, then at your ingress lb you wont need proxy protocol but only forwarded headers to pass the real ip.
 
 (you cant rely only on forwarded headers since a header can be forge)

**Comment by bcdrme** [comment]
I also tried to make it work, spent the day on it, and unfortunately it seems that it's a problem with Traefik itself cf https://github.com/traefik/traefik/issues/8304

**Comment by timothydlister** [comment]
With some help from this thread and Traefik support, I was successful in getting proxy support to work with Digital Ocean while maintaining "externalTrafficPolicy: cluster"; thus, working health checks for DigitalOcean load balancers. I'm using proxy support to apply ipwhitelist middlewares on my ingressroutes. For anyone else trying to do this, here are the changes I made to the helm values.
```
image:
  name: traefik
  tag: "2.5.1"

service:
  enabled: true
  type: LoadBalancer
  annotations:
    # This will tell DigitalOcean to enable the proxy protocol so we can get the client real IP.
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
  
additionalArguments:
  # Tell Traefik to only trust incoming headers from the Digital Ocean Load Balancers
  - "--entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
  - "--entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
  - "--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8"
  - "--entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8"

**Comment by kamikazechaser** [comment]
Additionally with @timothydlister's solution, I added a `service.beta.kubernetes.io/do-loadbalancer-hostname: "kube.your.tld"` annotation to get it working with cert-manager where `kube.your.tld` (can be any subdomain) is a dedicated A name pointing to the LoadBalancer public IP.

**Comment by joeldeteves** [comment]
@timothydlister I have an almost identical setup to yours - DO Managed K8s running behind a DO LB with Traefik ingress, my config file is the same as yours, I have `oroxyProtocol` working and `forwardedHeaders` enabled but I'm still only seeing interal IP addresses in the logs.

Do you have any idea what else might be missing from my setup?

**Comment by mloiseleur** [comment]
Hello,

It seems this issue is solved. 
Let us know if you think there is something we can do to help on this subject within this helm chart.

**Comment by badrdouah** [comment]
> additionalArguments:

Hi,
can you please help me where should i put the additional arguments,
 should it be in the LB service yaml root section 
thanx

**Comment by mloiseleur** [comment]
Hello @badrdouah 

It's in the root section.

**Comment by badrdouah** [comment]
> Hello @badrdouah
> 
> It's in the root section.

Hi @mloiseleur 
i'm using linode, hope this does not make a difference, i tried to put it in the root section but it is throwing error
`# * <nil>: Invalid value: "The edited file failed validation": ValidationError(Service): unknown field "additionalArguments" in io.k8s.api.core.v1.Service`

`apiVersion: v1
kind: Service
additionalArguments:
   - "--entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,10.120.0.0/16"
   - "--entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,10.120.0.0/16"
   - "--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,10.120.0.0/16"
   - "--entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,10.120.0.0/16"
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: default
    service.beta.kubernetes.io/linode-loadbalancer-enable-proxy-protocol: "true"
  creationTimestamp: "2022-11-17T22:36:26Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: traefik-default
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-20.3.0
  name: traefik
  namespace: default
  resourceVersion: "6028471"
  uid: dfebc3ae-c22c-4963-b8f6-4d2bf73c7e0c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.167.31.188
  clusterIPs:
  - 10.167.31.188
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    nodePort: 32140
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 31507
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-default
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: 139-144-264-29.ip.linodeusercontent.com
      ip: 139.144.264.29`

**Comment by mloiseleur** [comment]
@badrdouah You are editing a `Service` not values.yaml file for this helm chart. You may compare this Helm Chart output with your k8s object, if you need. You may ask for help on [traefik community forum](https://community.traefik.io/).

**Comment by badrdouah** [comment]
@mloiseleur i have tried the traefik forum , i got no help
your answer helped me a bit but still it's not working yet, 
what i did 
i did a clean install of traefik

> helm upgrade --install traefik  traefik/traefik --set "ports.websecure.tls.enabled=true"  --set "providers.kubernetesIngress.publishedService.enabled=true"    

then i applied the following values file 

```
image:
  name: traefik

service:
  enabled: true
  type: LoadBalancer
  annotations:
    # This will tell DigitalOcean to enable the proxy protocol so we can get the client real IP.
    service.beta.kubernetes.io/linode-loadbalancer-enable-proxy-protocol: "true"
  spec:
   # This is the default and should stay as cluster to keep the DO health checks working.
    externalTrafficPolicy: Cluster
  
additionalArguments:
  # Tell Traefik to only trust incoming headers from the Digital Ocean Load Balancers.
  - "--entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,10.120.0.0/16"
  - "--entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,10.120.0.0/16"
  # Also whitelist the source of headers to trust,  the private IPs on the load balancers displayed on the networking page of DO.
  - "--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,10.120.0.0/16"
  - "--entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,10.120.0.0/16"
```

> helm upgrade -f /Users/dbadr/Desktop/K8s/values.yaml traefik  traefik/traefik

in the values file i replaced 

>    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"

with

>    service.beta.kubernetes.io/linode-loadbalancer-enable-proxy-protocol: "true"

since im using linode not digital ocean provider
i'm still getting the load balancer ip address instad of client real ip address,

**Comment by antoniomyslice** [comment]
Using Kamal I got it working by entering the following:


`entryPoints.web.proxyProtocol.insecure: true
entryPoints.websecure.proxyProtocol.insecure: true`
