### ISSUE TITLE
NodePort on main service?

### ISSUE THREAD

**Issue by reesericci** [traefik/traefik-helm-chart#413]
Any way to use NodePort on the main service?

**Comment by Didr** [comment]
Hi,
Check out the values file.
https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

Try changing `type: LoadBalancer` value to `type: NodePort`:
```
service:
  enabled: true
  type: LoadBalancer
  ````
to
```
service:
  enabled: true
  type: NodePort
  ````

You also need to tell the NodePort which ports it should use, you can see those under the `ports` in the values file. There's one for each port.
https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L225
