### ISSUE TITLE
Default values file probably shouldn't have any ports actually defined

### ISSUE THREAD

**Issue by xaocon** [traefik/traefik-helm-chart#415]
It would be really helpful if the `ports` section of values.yaml didn't have any actual ports defined.

The major issue is that it's pretty common for people to subchart upstream in order to add customization. I see the logic in having helpful defaults but for values like maps and arrays the values are merged. As the information that is there is very helpful I'd recommend that it just be commented out and have the ports line changed to `ports: {}`. 

I actually suggested workaround in helm first and was told default values like this are considered bad practice helm/helm/issues/9597#issuecomment-819896909. 

I'd be happy to create a PR for this but considering it would change the way the chart works I wanted to get some input from maintainers first.

**Comment by mloiseleur** [comment]
Hello @xaocon,

Thanks for your report. We won't do that, it's not how Helm is intended to work.

**Comment by ben-turner** [comment]
This is a rather disappointing resolution. There is currently no way to disable the default web and websecure ports because `ports` is set as an object. No matter what you set it to, the values get merged and those two default ports get passed through.

In that linked thread, a member of the Helm project says
> If there are issues with the default values from a particular chart, I would propose opening a ticket with the chart maintainers to provide more sane defaults

so, I don't think this has anything to do with how Helm is or isn't intended to work.

**Comment by mloiseleur** [comment]
Hello @ben-turner,

You can disable web and websecure ports. For instance, you can see with this template command:
```
helm template traefik --set ports.web=null --set ports.websecure=null --set service.enabled=false traefik/traefik
```

That there is no web and websecure ports in the YAML generated files. 

Does it answer your need ?

**Comment by xaocon** [comment]
> Thanks for your report. We won't do that, it's not how Helm is intended to work.

Hey @mloiseleur, thanks for your work on the project.

It's your chart and you should handle it the way you want but if you want it to work the way that Helm is intended to work, you should check out the comment from a Helm maintainer in the issue I opened before I opened this issue. It's linked in the description of this issue.

**Comment by ben-turner** [comment]
I think I might actually be mistaken. Setting `null` works perfectly fine, even from within the values file (as opposed to the command line). I could have sworn that there was an issue with `null` being treated as `{}` and therefore merging did nothing, but I can't find any reference to that now so I must be wrong. My sincere apologies, this isn't nearly as much of an issue as I thought.

**Comment by mloiseleur** [comment]
So I understand it's ok for your @ben-turner. Cool !

Anything to add @xaocon  ?
