### ISSUE TITLE
Support configuring the GatewayAPI's Gateway namespace

### ISSUE THREAD

**Issue by ah-f3** [traefik/traefik-helm-chart#446]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

The `Gateway` is currently installed into the `default` namespace: 

Can a config value be added here: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L80-L86 to allow configuring this namespace?

https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/gateway.yaml#L7

Alternatively,  a flag to not install the Gateway and allow a user to install one outside the chart (possibly also not installing the GatewayClass?)

**Comment by juranir** [comment]
Did you tried to use the parameter "-n NamespaceName"?
Ex. helm install MyPackage -n MyNamespace

**Comment by ah-f3** [comment]
https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/gateway.yaml#L7 explicitly shows `default` so i'm not sure helm will override it.

Additionally, I don't want the Gateway in the namespace im installing traefik into.

**Comment by faust64** [comment]
Indeed, this could be worth patching.
If you're up for it, feel free to submit a PR.
I'll look into it otherwise.
