### ISSUE TITLE
Dual-Stack cluster, Helm chart results in SingleStack deployment

### ISSUE THREAD

**Issue by samip5** [traefik/traefik-helm-chart#453]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.0.2

### What version of Traefik are you using?

2.4.9

### What did you do?

1. Install dual-stack Kubernetes cluster.
2. Install Calico
3. Install Traefik using Helm

### What did you see instead?

I saw that the deployment from `helm install traefik traefik/traefik` results in a SingleStack deployment, and it doesn't get a IPv6 address when it should.

### What is your environment & configuration?

Platform/architecture: Raspberry Pi 4, running Ubuntu 20.04 LTS (arm64)
Kubernetes version: 1.21.x

Default Helm traefik values.

### Additional Information
After deployment I executed `kubeadm get svc traefik -o yaml` and the resulting output is:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-07-19T20:33:08Z"
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-10.0.2
  name: traefik
  namespace: default
  resourceVersion: "1335"
  uid: 831207c4-e46e-47d5-9c0a-6b85032cd36a
spec:
  clusterIP: 10.96.144.105
  clusterIPs:
  - 10.96.144.105
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    nodePort: 31611
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 30437
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```
This shouldn't have ipFamilies as IPv4 when the cluster is dual-stack configured, nor have ipFamilyPolicy as singleStack.

**Comment by dtomcej** [comment]
Hello @samip5,

The helm chart currently does not configure `ipFamilies` at all, and therefore you are seeing the default IPv4 settings generated by kubernetes.

Please feel free to open a PR to add dual stack capabilities to the service!

**Comment by samip5** [comment]
> Hello @samip5,
> 
> The helm chart currently does not configure `ipFamilies` at all, and therefore you are seeing the default IPv4 settings generated by kubernetes.
> 
> Please feel free to open a PR to add dual stack capabilities to the service!

Hello @dtomcej,

I have now opened a PR regarding this, and I have also tested that it works now like it should.
