### ISSUE TITLE
Annotation `prometheus.io/port` should be a string (instead of integer) in pod annotations

### ISSUE THREAD

**Issue by nykma** [traefik/traefik-helm-chart#455]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.1.0

### What version of Traefik are you using?

2.4.8

### What did you do?

```sh
$ helm repo update
# Copy 'metrics:' config from sample values.yaml to my values.yaml 
$ helm upgrade traefik traefik/traefik -f ./values.yaml --dry-run --debug
```

### What did you see instead?

```
history.go:56: [debug] getting history for release traefik
upgrade.go:123: [debug] preparing upgrade for traefik
Error: UPGRADE FAILED: unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found 9, error found in #10 byte of ...|io/port":9100,"prome|..., bigger context ...|metheus.io/path":"/metrics","prometheus.io/port":9100,"prometheus.io/scrape":"true"},"labels":{"app.|...
helm.go:81: [debug] unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found 9, error found in #10 byte of ...|io/port":9100,"prome|..., bigger context ...|metheus.io/path":"/metrics","prometheus.io/port":9100,"prometheus.io/scrape":"true"},"labels":{"app.|...
UPGRADE FAILED
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:157
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:80
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
```

### What is your environment & configuration?

K8s v1.20.4
helm v3.6.2

### Additional Information

The value of pod annotation `prometheus.io/port` should be string, but I noticed that, in this test case, a `number` is given:

https://github.com/traefik/traefik-helm-chart/commit/a3620f69afc59d01bc82eb52b85439f8e1344c11#diff-329428d075f4a89ca94227f2684715a85c62a935058dd0a9dd1f48bc8bde8f0aR56

Not sure if this is a bug or my own environment-related problem.

**Comment by Calvinaud** [comment]
Hello,
Not sure it's an environment-related problem, I have the same problem on my  environment and I was also able to reproduce it on a new Minikube environment without any values.yaml.

Look like the problem is coming from the chart v10.1.0.

For a quick fix, reverting to the  precedent version of the chart helm (v10.0.2) worked for me. 
```helm upgrade traefik -n traefik traefik/traefik --version v10.0.2```

**Comment by ncd** [comment]
I believe that this is the issue of helm chart v10.1.0 when they configure prometheus annotation, could you please help to fix the helm chart

**Comment by nykma** [comment]
I'm willing to, but I can't. I'm not familiar with this chart template language....

**Comment by SantoDE** [comment]
Fixed thanks to @jakubhajek
