### ISSUE TITLE
PodDisruptionBudget update to `policy/v1` apiVersion

### ISSUE THREAD

**Issue by z0rc** [traefik/traefik-helm-chart#458]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

```
policy/v1beta1 is deprecated since 1.21 and will be removed in 1.25
```
More at https://github.com/kubernetes/kubernetes/blob/v1.21.3/CHANGELOG/CHANGELOG-1.21.md?plain=1#L602

**Comment by rubroboletus** [comment]
Simply replace the line:
`apiVersion: policy/v1beta1`
with the following lines:
`{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}`
in pdb.yaml
