### ISSUE TITLE
ForwardAuth middleware not working with Keycloak

### ISSUE THREAD

**Issue by MarjanJordanovski** [traefik/traefik-helm-chart#462]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

latest

### What version of Traefik are you using?

latest

### What did you do?

I deployed traefik and keycloak on kubernetes. I created a client on keycloak and I want keycloak to protect access to my application. I created ingressroute, where my application is exposed, and that ingressroute is using middleware which is doing forwardauth to keycloak address (let's name it address1): 
https://mykeycloakURL/auth/realms/RELMNAME/protocol/openid-connect/auth?scope=openid&response_type=code&client_id=CLIENTID&redirect_uri=https://myprotectedapplicationURL/&prompt=consent
When I just enter this address1 to browser, proper login screen appears. But when I access my https://myprotectedapplicationURL , traefik does forwardauth toaddress1, but since login page returns status code 200 when loaded, traefik automatically navigates to https://myprotectedapplicationURL without waiting for successful authentication. How to fix this?

### What did you see instead?

-

### What is your environment & configuration?

k8s

**Comment by mnorrsken** [comment]
You cant use keycloak directly with forward auth as far as I know. You need to use something like oauth-proxy in between.

**Comment by jakubhajek** [comment]
Hello @MarjanJordanovski 

I think this is not related to the Helm Chart itself, I would encourage you to ask that question on our community forum.

Thank you,
