### ISSUE TITLE
Support for pod topology spread constraints

### ISSUE THREAD

**Issue by abatilo** [traefik/traefik-helm-chart#465]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Could we update the chart to support setting a pod topology spread constraint?
https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

**Comment by mloiseleur** [comment]
Hello @abatilo,

Thanks for your feature request. 
Does PR #663 fits your need ?
