### ISSUE TITLE
helm install pod ErrImagePull

### ISSUE THREAD

**Issue by jshum2479** [traefik/traefik-helm-chart#470]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

2.2.8

### What version of Traefik are you using?

2.2.8

### What did you do?

helm install traefik-operator traefik/traefik --namespace traefik

### What did you see instead?

helm install traefik-operator traefik/traefik --namespace traefik works fine, but the pod has error pull the image due to the rate limit exceeded.  I am behind a corporate firewall, so from docker hub perspective, it's coming from the same address and therefore exceeded the limit. 

`pod/traefik-operator-558d76fd9c-qkqzr   0/1     ErrImagePull   0          13s`

Failed to pull image "traefik:2.2.8": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

If I pulled the image manually, then the pod will run fine.   I tried to --set imagePullSecrets=regsecret  but doesn't help.

### What is your environment & configuration?

Local k8s cluster, minikube

**Comment by faust64** [comment]
Hi,

Your error message is pretty self-explainatory: `You have reached your pull rate limit.`

As of last year, if I'm not mistaken, pulling images out of docker.io is subject to some internal rate limit.

Sounds like you have hit your quota. You may try again later.
If you have another public IP (like a smartphone with tethering capabilities), you could use it pulling your images -- maybe import it into your Kubernetes nodes cache, then make sure the imagePullPolicy for your Pods is set to IfNotPresent.

Though maybe something could be done, from Traefik point of view: when publishing a release to DockerHub, consider pushing a copy to a "better" registry.
When deploying Kubernetes with Kubespray: all images are located in quay.io or k8s.gcr.io. As of Docker Labs introducing rate limits, you would really need an account, for their registry to remain reliable.
You don't need to be a company, with several IT guys or k8s clusters pulling images on a loop. I did experience with those errors, on personal clusters, only running CI jobs.

**Comment by jshum2479** [comment]
I believe the problem is because of my ip coming behind corporate firewall, it will be the same. If I pulled the image manually then I don't have a problem.   We are developing a UI tool for novice user to installing ingress controller.  I agreed if the traefik image is in another registry then it will be easier,  we have done similar thing for our images.

**Comment by robertpatrick** [comment]
We are trying to pass an imagePullSecret to the traefik helm chart so that the Docker Hub pull is not does as an anonymous user.  Unfortunately, we haven't been able to figure out how to get this included in the generated deployment .spec.template.  

We have tried specifying it with `--set 'deployments.imagePullSecrets={name: dockerhub}'` and with `-f values.yaml` where the values.yaml file looks like this:

```yaml
deployments:
    imagePullSecrets:
        - name: dockerhub
```

Unfortunately, nothing we have tried causes the imagePullSecret to show up in the generated deployment object.

**Comment by robertpatrick** [comment]
In other places, we specify the Docker Hub credentials to get around the rate limiting problem that is imposed on anonymous user pull requests.  You should be able to:

1. Create a docker-registry secret for Docker Hub in the `default` namespace.
2. Specify the `imagePullSecrets` when installing traefik via the helm chart.

For example:

```
% kubectl create secret docker-registry dockerhub --docker-server=https://index.docker.io/v1/ --docker-username=<username> --docker-email=<email> --docker-password=<password>
% helm install traefik traefik/traefik --set "deployment.imagePullSecrets[0].name=dockerhub"
``` 

This results in a pod spec with imagePullSecrets set like this:

```
apiVersion: v1
kind: Pod
...
spec:
  ...
  imagePullSecrets:
  - name: dockerhub
  ...
```

This should allow you to work around the rate limitation.

**Comment by jshum2479** [comment]
Thanks @robertpatrick.   I was using an older version of the chart and therefore even if I set the pull secrets the same doesn't work.  closing this now.
