### ISSUE TITLE
Possibility to change readiness/liveness probes through values

### ISSUE THREAD

**Issue by andreasvikke** [traefik/traefik-helm-chart#479]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I've run into a problem where some pods restart due too high demand in node. The httpGet probes get timeout cause it's too slow to startup on node. Therefore i suggest the possibility to change readiness/liveness probes trough values.

This is the section of code that would be nice to change. I'd like to change the httpGet to a exec with curl like explained in this comment https://github.com/kubernetes/kubernetes/issues/89898#issuecomment-876539217
https://github.com/traefik/traefik-helm-chart/blob/bf315e74c8132ab74a5567b6cbf217e59a724c3c/traefik/templates/_podtemplate.tpl#L45-L62

**Comment by jakubhajek** [comment]
We discussed that issue on PR #480 and replacing httpGet health probe to exec does not solve the problem described in that issue. No need to change the existing healthprobes.
