### ISSUE TITLE
More than one replica with acme certificateresolver

### ISSUE THREAD

**Issue by m-shaffer** [traefik/traefik-helm-chart#485]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello,

The chart is currently configured to fail with the message "You can not enable acme if you set more than one traefik replica" if you are using acme resolver and want more than 1 replica. Both the acme integration and the ability for a high availability deployment are valuable.

Is there any reason to fail in this state if using a RWX volume for acme.json shared amongst more than 1 replica? If yes is there any other workaround for creating either a daemonset or deployment with replicas greater than 1 while using an acme resolver?

Thanks

**Comment by faust64** [comment]
Hi,

To my knowledge, the risk of sharing a RWX volume storing certificates for several Traefik instances is that:

- multiple instances may request a new certificate together (say client A queries site A on Traefik A, client B site B on Traefik B)
- multiple instances may try to renew the same certificates simultaneously

Either way, there is a risk for corrupting your database.

**Comment by jakubhajek** [comment]
Hello! 

We have open [PR](https://github.com/traefik/traefik/pull/7351) to move TLS certificates to Kubernetes secretes instead of storing them in a file. Traefik is stateless so there should be no persistence data. 

However, scaling up Traefik is challenging in the context of issuing certificates from ACME. That should be a leader elected otherwise the process of getting certificates will fail because there is no certainty if the request from ACME will reach the same instances that start the challenge process.

**Comment by diepes** [comment]
> Hello!
> 
> We have open [PR](https://github.com/traefik/traefik/pull/7351) to move TLS certificates to Kubernetes secretes instead of storing them in a file. Traefik is stateless so there should be no persistence data.
> 
> However, scaling up Traefik is challenging in the context of issuing certificates from ACME. That should be a leader elected otherwise the process of getting certificates will fail because there is no certainty if the request from ACME will reach the same instances that start the challenge process.

@jakubhajek moving the TLS certificate to Secrets sounds like a great idea.
I think the leader could be avoided as follows, using the Secret as a state store until cert received.

For each/any Traefik instance.
1. Receive trigger for new cert.
2. Check for existing Secret containing the cert+key 
    1. If no Secret: Create Secret for the cert - empty state annotation? - starting letsencrypt for Traefik_Instance_X @Time
    2. If Secret is there but no key, only state that other Traefik Instance is busy, just verify @Time < 10min ago
    3. If the secrets contains a valid key+cert copy to local instance ?
4. Active Traefik instance does the TLS ALPN auth, and places the info needed for the TLS auth in the secret.
5. Any Traefik instances receives the TLS ALPN auth request from LetsEncrypt, takes the info in the secret and responds.
    1. and then completes the Secret with the correct cert + key info.
