### ISSUE TITLE
traefik dashboard 404 page not found

### ISSUE THREAD

**Issue by A491382** [traefik/traefik-helm-chart#492]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

https://%{KUBERNETES_API}%/static/charts/traefik-9.18.2.tgz

### What version of Traefik are you using?

v2

### What did you do?

I setup my k3s with one master and one agent . I want to look around the traefik dashboard , but always got 404 page not found .

### What did you see instead?

I follow the readme at the https://github.com/traefik/traefik-helm-chart page , no mater port-forward or create new ingressourte , I got the same issue "404 page not found" . Hope let me know anything I missed , thanks

### What is your environment & configuration?

![image](https://user-images.githubusercontent.com/25001207/131307697-99a3e1dd-1b22-4353-a4cc-8b5441434cf4.png)

![image](https://user-images.githubusercontent.com/25001207/131307728-aaaa8e9a-0e73-4eed-8345-6131aa7693a9.png)

![image](https://user-images.githubusercontent.com/25001207/131307945-8766b7c2-d822-4c87-8b78-2e361ddb74ce.png)

![image](https://user-images.githubusercontent.com/25001207/131308429-edd1989a-d0e0-457f-800f-269099ce2834.png)

### Additional Information

```shell
I supposed missing some configurations to turn on the dashboard , but not sure where or how to turn on it , I set dashboard.enabled=trure in the  /var/lib/rancher/k3s/server/manifests/traefik.yaml, looks it now worked
```

**Comment by faust64** [comment]
In your screenshots, HelmChart, values passed to the Traefik chart, we can read:

```
dashboard
  enabled: false
```

Change that to `true`, to get the IngressRoute installed by Helm.

Since you're kubectl port-forward goes to port 9000: you're connecting to the traefik entrypoint. Your IngressRoute refers to the web entrypoint. This probably explains your 404.

**Comment by A491382** [comment]
thanks a lot  @faust64  , it works now
