### ISSUE TITLE
Helm install with experimental feature enabled does not work

### ISSUE THREAD

**Issue by vasanthaganeshk** [traefik/traefik-helm-chart#493]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.3.2

### What version of Traefik are you using?

2.5.1

### What did you do?

I tried to install traefik with gateway enabled.

```
helm install traefik --set experimental.kubernetesGateway.enabled=true traefik/traefik  -n kube-system
```

### What did you see instead?

```
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Gateway" in version "networking.x-k8s.io/v1alpha1", unable to recognize "": no matches for kind "GatewayClass" in version "networking.x-k8s.io/v1alpha1"]
```

### What is your environment & configuration?

I'm using K3s version v1.21.4+k3s1. As for the values.yaml, I tried doing with and without it. I got the same error.

**Comment by hannius** [comment]
May be you should install the crds of  [networking.x-k8s.io](https://github.com/kubernetes-sigs/gateway-api/blob/v0.3.0/config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml)
