### ISSUE TITLE
TLS default certificate in conjunction with cert-manager

### ISSUE THREAD

**Issue by awuetz** [traefik/traefik-helm-chart#512]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello all,

we are using traefikv2 with the helm charts in kubernetes in conjunction with cert-manager.

Now we want to have this default cert (https://doc.traefik.io/traefik/https/tls/#default-certificate) to not be generated. 
How can we achieve this, without creating a cert by ourself (and storing in e.g. a secret) but using the cert-manager generated cert.

Kind regards
Alex

**Comment by rtribotte** [comment]
Hello @awuetz,

Thanks for your interest in Traefik!

From what I can understand from your description, you should be able to reference a secret created by cert-manager from a TLSStore resource, which allows you to specify the default certificate. Please take a look at the [TLSStore documentation](https://doc.traefik.io/traefik/v2.5/routing/providers/kubernetes-crd/#kind-tlsstore).
