### ISSUE TITLE
Chart needs flag to enable external services on kubernetesingress provider

### ISSUE THREAD

**Issue by oskapt** [traefik/traefik-helm-chart#521]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

traefik-10.6.1

### What version of Traefik are you using?

traefik:2.5.3

### What did you do?

Deployed an Ingress that consumes an externalName Service.

### What did you see instead?

```
time="2021-11-07T23:03:24Z" level=error msg="Cannot create service: externalName services not allowed: traefik/local-demo-http" providerName=kubernetes ingress=rancher-demo namespace=traefik serviceName=local-demo-http servicePort="&ServiceBackendPort{Name:,Number:80,}"
```

### What is your environment & configuration?

- K3s v1.21.5+k3s2

### Additional Information

The chart has a flag for `providers.kubernetescrd.allowExternalNameServices=true` but does not have a flag for `providers.kubernetesingress.allowExternalNameServices=true`. 

In order to consume an externalName Service from an Ingress, the chart must be deployed with `--set "additionalArguments={--providers.kubernetesingress.allowExternalNameServices=true}"`.

**Comment by faust64** [comment]
Hi,

Sorry for the late answer.
You're right, we're missing that option ... I've submitted a PR ( #529 ) that should fix this.
