### ISSUE TITLE
kubernetesingress provider is missing ingressclass setting

### ISSUE THREAD

**Issue by electrical** [traefik/traefik-helm-chart#547]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

According to https://doc.traefik.io/traefik/providers/kubernetes-ingress/#ingressclass it's a valid setting still and i've been using it in my current deployments ( non helm based )
While investigating if I can move to the helm chart i found that this is missing.

**Comment by faust64** [comment]
Currently, you could deploy Traefik with an IngressClass provisioned by Helm, setting this:
https://github.com/traefik/traefik-helm-chart/blob/5d97a2e30076302950c31fc9a98f267bdd624fe8/traefik/values.yaml#L68-L70

And you may integrate with an existing IngressClass setting that one:
https://github.com/traefik/traefik-helm-chart/blob/5d97a2e30076302950c31fc9a98f267bdd624fe8/traefik/values.yaml#L221-L222

Is this what you were looking for?

**Comment by faust64** [comment]
Oh... and that https://github.com/rancher/helm-unittest/pull/12 was merged, I see?
Maybe we should take another shot at unit testing this ...

**Comment by electrical** [comment]
Hi, I did find the additionalArguments part and i'm now using that.
Perhaps I don't fully understand how the separate `IngressClass` resource works since I've never used it.
I expected there to be a setting for the ingressClass like the `kubernetesCRD` setting has.
