### ISSUE TITLE
Enable TLS Support by default on websecure port

### ISSUE THREAD

**Issue by MoBlockbuster** [traefik/traefik-helm-chart#560]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Does it make any sense to disable TLS support for traefik in the defaultconfig?
I mean this line: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L312 .

I would suggest to change this from false -> true.
If you agree with my suggestion I would create a Pullrequest to change this value.

BR

**Comment by mloiseleur** [comment]
Hello @MoBlockbuster,

Yes, it definitely make sense to enable `tls` on `websecure` endpoint. It's a breaking change, so it will need a major version bump in the PR.

**Comment by MoBlockbuster** [comment]
Hi @mloiseleur thanks.

This is my related PR: https://github.com/traefik/traefik-helm-chart/pull/657
