### ISSUE TITLE
Add kustomization.yaml to crds directory and make installation of CRDs an optional flag in values.yaml

### ISSUE THREAD

**Issue by oskapt** [traefik/traefik-helm-chart#568]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

In a GitOps scenario (or anything that uses Kustomize), when someone is installing Traefik and _also_ installing Middleware or other configuration that depends on the CRDs, Kustomize will currently fail the install on a dry-run because it doesn't have CRDs for the custom resources. 

If we drop a `kustomization.yaml` file into the crds directory, then the CRDs can be installed before the chart. If we also add a flag to `values.yaml` like `installCRDs: true` then they can be disabled during the chart installation if they were installed separately. 

This will be friendlier for the community who currently have to resort to hacky workarounds like downloading the CRDs and shipping them separately from the chart (which is how K3s does it), or having a 2-pass installation for common Middleware that goes in after the chart itself. It will make it easier to bootstrap and upgrade clusters.

**Comment by mloiseleur** [comment]
Hello @oskapt ,

We added [recently](https://github.com/traefik/traefik-helm-chart/pull/649) a kustomization.yaml file into this chart. 

Does it answer your need ?

**Comment by oskapt** [comment]
> We added [recently](https://github.com/traefik/traefik-helm-chart/pull/649) a kustomization.yaml file into this chart.
> 
> Does it answer your need ?

I don't know. I opened this issue eight months ago when I worked for Traefik. I no longer work there, nor do I use Traefik in a way that I can test this. I don't remember the specifics of the issue, but in a cursory glance, you probably still need a way to disable CRD installation in the Helm chart itself for the `kustomization.yaml` to be useful on its own. But maybe I'm wrong...like I said, I don't remember the details of how I wanted to use it.

You can close this issue if you think it's resolved.

**Comment by mloiseleur** [comment]
For testing and dry-run, it's now possible to install CRD with one command:
```bash
kubectl apply --server-side --force-conflicts -k https://github.com/traefik/traefik-helm-chart/traefik/crds/
```
There's no need to disable CRD installation, according to [helm documentation](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/).
