### ISSUE TITLE
Update Traefik 2.6.2 on Rancher partner charts

### ISSUE THREAD

**Issue by ddtmachado** [traefik/traefik-helm-chart#574]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

We need to update the [Rancher partner repo](https://github.com/rancher/partner-charts) again as they need the new s390 platform support available in 2.6.2.

**Comment by kevinpollet** [comment]
Closed by https://github.com/rancher/partner-charts/pull/377
