### ISSUE TITLE
CRDs in repo don't match CRDs from reference documentation

### ISSUE THREAD

**Issue by z0rc** [traefik/traefik-helm-chart#577]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.19.0

### What version of Traefik are you using?

2.6.2

### What did you do?

Tried to create Middleware CR
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-compress
spec:
  compress:
    minResponseBodyBytes: 1200
```

### What did you see instead?

`unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Middleware.spec.compress): unknown field "minResponseBodyBytes" in us.containo.traefik.v1alpha1.Middleware.spec.compress`

### What is your environment & configuration?

EKS 1.21, traefik deployed as helm chart.

### Additional Information

https://github.com/traefik/traefik-helm-chart/blob/v10.19.0/traefik/crds/middlewares.yaml doesn't match what defined at https://doc.traefik.io/traefik/reference/dynamic-configuration/kubernetes-crd/.

This is single instance of known mismatch, but I assume there is more, as there seems to be no automation or established process of updating CRDs in this repo.

While we're at it. Again I'm asking you to properly announce changes to CRDs in this repo. Bump chart major version and provide update instructions. Previous [request](https://github.com/traefik/traefik-helm-chart/pull/558#issuecomment-1035989766) was ignored.

**Comment by kevinpollet** [comment]
Hello @z0rc,

Thanks for your interest in Traefik,

> While we're at it. Again I'm asking you to properly announce changes to CRDs in this repo. Bump chart major version and provide update instructions. Previous https://github.com/traefik/traefik-helm-chart/pull/558#issuecomment-1035989766 was ignored.

Can you open a dedicated issue describing your proposal?

**Comment by z0rc** [comment]
@kevinpollet done.
