### ISSUE TITLE
Please consider using ghcr.io, docker hub is getting too restrictive

### ISSUE THREAD

**Issue by cornfeedhobo** [traefik/traefik-helm-chart#589]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I would like traefik to be pullable in all scenarios, but docker's increased concerns with money are leading to rather restrictive cloud flare lock outs. Would you please consider getting the docker images published to github's container registry as well, and then offering a toggle in the helm chart?

**Comment by kevinpollet** [comment]
Hello @cornfeedhobo,

Thanks for your interest in Traefik,

As stated in https://github.com/traefik/traefik/issues/8149#issuecomment-110891153, we are investigating the possibility, and we will take action on the Helm chart accordingly.

**Comment by mloiseleur** [comment]
In the meantime, I'll close this issue since it's already tracked on traefik repo.
