### ISSUE TITLE
IngressClass not installed when using custom Traefik image with tag < 2.3.0

### ISSUE THREAD

**Issue by flyte** [traefik/traefik-helm-chart#592]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.19.5

### What version of Traefik are you using?

2.6.6

### What did you do?

Installed the helm chart with:

```yaml
image:
  name: <my image with plugins>
  tag: 0.0.6
ingressClass:
  enabled: true
```

### What did you see instead?

The helm chart does not install `ingressclass.yaml` because of the following line (presumably):

```{{- if and .Values.ingressClass.enabled (semverCompare ">=2.3.0" (default .Chart.AppVersion .Values.image.tag)) -}}```

### What is your environment & configuration?

n/a

**Comment by flyte** [comment]
Confirmed, that if I change my image tag to `2.6.6009` it does install the IngressClass, but it's quite an unintuitive workaround.

**Comment by flyte** [comment]
Oh, that's a shame. A simple solution might have just been to add a
"traefikVersion" value that's set to the tag by default, to decouple the
image tag from the traefik version.

What is a supported way to build custom plugins into a container image for
deployment by this Helm chart then, since there is a flag in the
"experimental" values which enables custom plugins?

Thanks for your time.

**Comment by flyte** [comment]
Oh, that's a shame. A simple solution might have just been to add a
"traefikVersion" value that's set to the tag by default, to decouple the
image tag from the traefik version.

What is a supported way to build custom plugins into a container image for
deployment by this Helm chart then, since there is a flag in the
"experimental" values which enables custom plugins?

Thanks for your time.

**Comment by ddtmachado** [comment]
@flyte Regarding plugins you can share them with all replicas using a volume mount, its the `additionalVolumes:` key in the values config

**Comment by flyte** [comment]
Ah yes, I do recall reading this somewhere now. Thank you again.
