### ISSUE TITLE
missing ingressclass configuration for ingress

### ISSUE THREAD

**Issue by gioppoluca** [traefik/traefik-helm-chart#597]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.15.0

### What version of Traefik are you using?

2.6.1

### What did you do?

installed and configured the ingressclass but supposed that in the Ingress provider could be possibile to specify the ingressclass value.

### What did you see instead?

The ingresses did not get picked up by ingress controller
see this bug:
https://github.com/traefik/traefik/issues/9008

### What is your environment & configuration?

rancher 2.6.1 kuberentes 1.21.7

### Additional Information

```shell
It could be useful not to have to add the additionalArguments but to specify the ingressClass in the place where is more intuitive in helm values = providers.kubernetesingress.ingressclass
```

**Comment by kevinpollet** [comment]
Hello @gioppoluca,

Thanks for your interest in Traefik,

We already support an `ingressClass` option for the `kubernetesIngress` provider as described here https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L145.

According to this, we will close this issue.
