### ISSUE TITLE
Link to GitHub Repo on documentation page?

### ISSUE THREAD

**Issue by mfriess2** [traefik/traefik-helm-chart#599]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Would it be possible to put a link to the github repo on the documentation page: https://helm.traefik.io/traefik ?

Because if you have a local chart which references this URL and clicking on it and you want to know details like which traefik version is included in which chart version, then newbies are lost.

**Comment by mloiseleur** [comment]
Hi @mfriess2,

Thanks for your interest in Traefik !

Wdyt about the linked PR ?

**Comment by mfriess2** [comment]
Great, thank you!
