### ISSUE TITLE
Default ingressClass

### ISSUE THREAD

**Issue by rektide** [traefik/traefik-helm-chart#600]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello. I'm not sure, but would it perhaps be good to create a default `IngressClass` in this chart?

I'm looking at k3s-io/k3s#5562 and this feels like a potential issue that could effect everyone running a recent Kuberentes & this chart.

This would build off #576's IngressClass support.

**Comment by SantoDE** [comment]
That looks fairly fine to build. You wanna give it a go @rektide ?

**Comment by TheBigBear** [comment]
@rektide, I am so new to Kubernetes and trying my first k3s rollout of redhat's latest AWX and I am wondering if my k3s ingress not working is because of this issue? Can you comment if what I experience with my 'bad gateway' error Is related to this? https://gist.github.com/dmccuk/098fccc488c8a5aeaa5f859855660018?permalink_comment_id=4212831#gistcomment-4212831

**Comment by brandond** [comment]
I noticed there's still a comment in the chart that says its blocked by a PR on the rancher side: https://github.com/traefik/traefik-helm-chart/blob/20d3acaa196acdfc3c96e453aba24e901b1b2781/traefik/values.yaml#L83-L86

This PR (https://github.com/rancher/helm-unittest/pull/12) was merged 18 months ago; I don't see any reason why it couldn't be enabled now? I think K3s users would probably benefit from it.

**Comment by mloiseleur** [comment]
Hello @brandond,

Thanks for your interest in Traefik. 
This comment is outdated. With PR #638 , we've switched to https://github.com/quintush/helm-unittest
=> We're able to test on `Capabilities`. 

I agree with you: I don't see any reason either.

**Comment by brandond** [comment]
I see y'all have been making a lot of changes to the chart. We just recently updated k3s to v12.0.0 of the chart, but it's already moved up several major versions in the last two weeks - more change than we've seen in quite a while. We'd like to do a better job of keeping the embedded version of Traefik up to date, but it's hard to know what to target when it's changing so quickly. Would you have time at some point in the next week or two for us to sync up on the Rancher or Kubernetes slacks workspaces?

**Comment by mloiseleur** [comment]
@brandond Yes, sure, ping me on the Kubernetes Slack.

**Comment by mloiseleur** [comment]
@brandond @rektide IngressClass by default is on its way, see #693.
