### ISSUE TITLE
Something UDP-related is broken in 2.7.1 

### ISSUE THREAD

**Issue by faangbait** [traefik/traefik-helm-chart#610]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.21.1

### What version of Traefik are you using?

2.7.1

### What did you do?

I have a couple active UDP entrypoints/ingressroutes. I was prevented from upgrading the helm chart to the latest version. Last upgrade was 19 days ago, and it was successful.

### What did you see instead?

The error thrown is, "Error: UPGRADE FAILED: Service "traefik-udp" is invalid: spec.ports: Required value"

Inspecting the config revealed that this Service is being specified with an invalid configuration.

https://github.com/traefik/traefik-helm-chart/blob/9da111bb8b44513a8623cba7a50cb353cba77309/traefik/templates/service.yaml#L102

### What is your environment & configuration?

https://github.com/faangbait/antennae/tree/main/k8s

Values are in /infrastructure/traefik-values.yaml

### Additional Information

```shell
The spec.ports array is empty. I think it probably needs to generate ports: {} instead of just a blank key.

When I remove the UDP entrypoints, installation proceeds as expected.
```

**Comment by faangbait** [comment]
```
service:
  enabled: false
```

also fixes it, but that's certainly not what I'm after.

**Comment by mloiseleur** [comment]
Hello @faangbait,

Thanks for your report. No, you're not.
 It's true that this charts needs at least one exposed port in order to deploy traefik service.
