### ISSUE TITLE
dashboard entrypoints

### ISSUE THREAD

**Issue by yidongw** [traefik/traefik-helm-chart#612]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

3.5.0

### What version of Traefik are you using?

2.6.6

### What did you do?

N/A

### What did you see instead?

N/A

### What is your environment & configuration?

N/A

### Additional Information

```shell
This PR https://github.com/traefik/traefik-helm-chart/pull/100 is Exposing dashboard by default but only on traefik entrypoint.

I put a similar comment in that PR as well.

I understand what you guys want to do, and I know that we can either use port-forward or create an IngressRoute to expose the dashboard, but how is `traefik/templates/dashboard-hook-ingressroute.yaml` useful at all?

I spent hours trying to figure out how to use the `dashboard-hook-ingressroute.yaml` to expose the dashboard.
My intuition is that if there is an IngressRoute that is kinda doing the exposing thing, I must be able to mutate it a little in order for me to access it from the Service.

The answer is I can't. `dashboard-hook-ingressroute.yaml` is now become useless.

I would suggest either removing `dashboard-hook-ingressroute.yaml` from the templates because it is causing confusion for people like me or making `entryPoints` changeable so we can actually use that chart.
```

**Comment by mloiseleur** [comment]
Hello @yidongw 
Thanks for your interest in Traefik !
You're right, you cannot modify object managed by this Helm Chart. 
As you have guessed, this `IngressRoute` is used to provide an easy-to-go access to dashboard, without security issues.
This Helm Chart is designed to help when installing traefik, not managing `IngressRoute`. The dashboard is not an exception to this design.
