### ISSUE TITLE
https://helm.traefik.io/traefik is down

### ISSUE THREAD

**Issue by manuelottlik** [traefik/traefik-helm-chart#624]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

-

### What version of Traefik are you using?

-

### What did you do?

-

### What did you see instead?

-

### What is your environment & configuration?

-

**Comment by ldez** [comment]
Hello,

Thank you, we will fix that quickly.

**Comment by manuelottlik** [comment]
Thank you, and sorry for so little info in the issue, was in the middle of a deployment.

**Comment by victorboissiere** [comment]
We have an impact on our deployments as well

**Comment by unlightable** [comment]
:(

**Comment by sidineyc** [comment]
Any ETA ?

**Comment by ldez** [comment]
We are still working on.

**Comment by ldez** [comment]
The plugin services are restored.
The hem chart is restored.

The other services will come back quickly.

Sorry for the service interruption.

**Comment by ldez** [comment]
All services are up now.

Sorry for the service interruption.
