### ISSUE TITLE
helm.traefik.io is down

### ISSUE THREAD

**Issue by merouanekhalili** [traefik/traefik-helm-chart#629]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

2.6

### What version of Traefik are you using?

2.6

### What did you do?

Try to update my helm repo

### What did you see instead?

Error: looks like "https://helm.traefik.io/traefik" is not a valid chart repository or cannot be reached: Get "https://helm.traefik.io/traefik/index.yaml": EOF

### What is your environment & configuration?

YAML

**Comment by darkweaver87** [comment]
Hello,

Thanks for reporting the issue. From where are you trying to reach our helm repo ?
Is it still happening ?

Rémi

**Comment by ldez** [comment]
no feedback, and the helm chart works, so I think we can close.
