### ISSUE TITLE
How to use daemonset type install traefik?

### ISSUE THREAD

**Issue by fengfuyun52** [traefik/traefik-helm-chart#64]
Hello there,
I want to know that how can we use daemonset type install traefik?
Thanks very much!

**Comment by prima101112** [comment]
why you want to install traefik as daemonset?
it could be done by manually modify the templates but by defaukt traefik will run as standard deployments i think.

**Comment by travisghansen** [comment]
Several reasons potentially, as I see it generally `DaemonSet` would likely be used in environments that:

- Do not have support for `LoadBalancer` services

and/or

- Are fronting the cluster with an external/existing load balancer

It's certainly not uncommon for `Ingress` controllers to be installed as a `DaemonSet` using host networking.

**Comment by Fank** [comment]
Another reason, installing a microk8s on a single vm and wanted to use traefik as default ingress controller.

**Comment by acim** [comment]
Yes, this would be really nice to have for self-managed clusters with no LoadBalancer service by cloud provider, for example Hetzner Cloud. By the way, nginx-ingress chart has DaemonSet possibility.

**Comment by toabi** [comment]
The documentation until v2 explicitly mentioned a DaemonSet install: https://docs.traefik.io/v1.7/user-guide/kubernetes/#deploy-traefik-using-a-deployment-or-daemonset

> If you are unsure which to choose, start with the Daemonset.

Our use case for DaemonSet-Install:

Cluster in EKS with two Node Pools:

Pool 1: Workers - Not put in any target group
Pool 2: Ingress Nodes - Automatically spawn into a "ingress" target group and get node label `app=ingress`

We then would install traefik as DaemonSet on app=ingress Nodes and provision an terraform-managed ALB with forwards to that target group.

At least that was the way to go with ingress-nginx and it was nice. But now we need more features from our ingress controller.

**Comment by davidalger** [comment]
Fixed by #298

**Comment by jakubhajek** [comment]
Thank you @davidalger for the #298, which allows using Deamonset with Traefik.
