### ISSUE TITLE
ingressendpoint ip setting is being ignored

### ISSUE THREAD

**Issue by fenio** [traefik/traefik-helm-chart#647]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

11.1.0

### What version of Traefik are you using?

2.9.1

### What did you do?

I'm trying to configure traefik as my ingress for home k8s based lab and I'm trying to assign the only public IP I've got to it.
Seems it's simply being ignored.

I'm trying to add it using https://doc.traefik.io/traefik/v2.9/providers/kubernetes-ingress/#ip

helm upgrade --install traefik traefik/traefik --create-namespace --namespace traefik --set "ports.websecure.tls.enabled=true" --set "providers.kubernetesIngress.ingressEndpoint.ip=11.12.13.14"

I'd expect it to be used for all ingresses I'm creating later on.

### What did you see instead?

If I create ingress I end up without IP being assigned to it:

  status:
    loadBalancer: {}

It seems to be completely ignored. I can't find any place in rendered template where such IP would be referenced.

### What is your environment & configuration?

 (fenio@debian) ➜   kubectl version           
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"archive", BuildDate:"2022-04-02T14:49:13Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:12:04Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}

 (fenio@debian) ➜  helm version
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}

**Comment by mloiseleur** [comment]
Hello @fenio 

Thanks for your detailed report. 

This parameter is currently not implemented in the chart. You can workaround this using additionalArguments, for instance with this values file:
```yaml
ports:
  websecure:
    tls:
      enabled: true
providers:
  kubernetesIngress:
    ingressEndpoint:
      ip: "11.12.13.14"
additionalArguments:
  - --providers.kubernetesingress.ingressendpoint.ip=11.12.13.14
```

**Comment by mloiseleur** [comment]
Does this works for you ?

**Comment by fenio** [comment]
Thanks for your reply @mloiseleur .
Yeah that worked.

In case someone wants to use it from command line it needs to be defined in such a way:

`--set additionalArguments='{--providers.kubernetesIngress.ingressEndpoint.ip=11.12.13.14}' `
