### ISSUE TITLE
Setting `ports.web.proxyProtocol.insecure=true` doesn't work

### ISSUE THREAD

**Issue by z0rc** [traefik/traefik-helm-chart#678]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

16.2.0

### What version of Traefik are you using?

2.9.1

### What did you do?

Setting value `ports.web.proxyProtocol.insecure=true`.

### What did you see instead?

`--entrypoints.web.proxyProtocol.insecure` isn't added to args in rendered Deployment resource.

### What is your environment & configuration?

Irrelevant, as this is observable with `helm template`

### Additional Information

There is some bug in conditional logic around `proxyProtocol` and `tls` values.

Setting `ports.websecure.proxyProtocol.insecure=true` works as expected, `--entrypoints.websecure.proxyProtocol.insecure` is added to Deploymnet's args.

Setting both `ports.web.proxyProtocol.insecure=true` AND `ports.web.tls.enabled=true` produces both `--entrypoints.web.http.tls=true` and `--entrypoints.web.proxyProtocol.insecure` added to args. Which hints that there is some issue in condition logic.

Followup to https://github.com/traefik/traefik-helm-chart/pull/673.

**Comment by mloiseleur** [comment]
Hello @z0rc,

Thanks for this detailed issue. 
@hesstobi What do you think about it ? How about adding a (graceful) `fail` in those cases ?

**Comment by hesstobi** [comment]
@mloiseleur  Oh damn, i miscounted the if conditions and didn't test it for the web entrypoint. These setting should not be dependent on the tls setting. #682 should fix this.
