### ISSUE TITLE
ServiceMonitor selector should also use `app.kubernetes.io/instance` label

### ISSUE THREAD

**Issue by z0rc** [traefik/traefik-helm-chart#680]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

16.2.0

### What version of Traefik are you using?

2.9.1

### What did you do?

I have two traefik deployments in single namespace. One is behind internet facing loadbalancer, another is behind internal loadbalancer. I need a way deploy ServiceMonitor for each deployment.

### What did you see instead?

ServiceMonitor selector matches both internal and internet-facing traefik deployments simultaneously.

### What is your environment & configuration?

Irrelevant.

### Additional Information

ServiceMonitor by default should use same selector as PodDisruptionBudget, https://github.com/traefik/traefik-helm-chart/blob/v16.2.0/traefik/templates/poddisruptionbudget.yaml#L14-L16. This way it will pick pods relevant only to current deployment.

Followup to https://github.com/traefik/traefik-helm-chart/pull/425.

**Comment by mloiseleur** [comment]
Thanks for your report @z0rc 
It should be fixed with v17.0.1
