### ISSUE TITLE
helm --namespace option not working

### ISSUE THREAD

**Issue by seuf** [traefik/traefik-helm-chart#690]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

traefik-16.1.0

### What version of Traefik are you using?

traefik:2.9.1

### What did you do?

```
helm --namespace template traefik traefik.traefik
```

### What did you see instead?

no namespace specified in resources

### What is your environment & configuration?

local environment, just `helm -n traefik template traefik traefik/traefik`

### Additional Information

```shell
namespace should be set to traefik in all resources (except cluster role)
```

**Comment by thechristschn** [comment]
I guess this would be solved with https://github.com/traefik/traefik-helm-chart/pull/373

It is a slightly different use case, but at the end it will add `{{ .Release.Namespace }}` to all resources and that is what is needed here.

**Comment by mloiseleur** [comment]
It's an expected behavior from helm 3, see [this issue](https://github.com/helm/helm/issues/5628) for more details.

**Comment by mloiseleur** [comment]
Starting with v20.2.0, it's possible to override Helm namespace on this Chart. See #718 for details.

**Comment by seuf** [comment]
Hi @mloiseleur I've retried the latest (v20.3.0 release) and the serviceAccount resource is still created in the default namespace..
