### ISSUE TITLE
Changelog Breaking Changes & Upgrade Details

### ISSUE THREAD

**Issue by rgstephens** [traefik/traefik-helm-chart#701]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I'm on `10.24` of the helm chart and want to upgrade. The [Upgrading](https://github.com/traefik/traefik-helm-chart#upgrading) section of the README.md states that `New major version indicates that there is an incompatible breaking change`. The changelog shows **nine** major releases since the `10.24` release.

- Do all of these releases introduce breaking changes?
- What are the breaking changes (the word `breaking` isn't in the changelog).

The [PR](https://github.com/traefik/traefik-helm-chart/pull/661#issue-1405733290) that adds the change log states `When users upgrade, it's not easy to understand what has changed, especially on breaking changes.`

I think that's still the case.

**Comment by mloiseleur** [comment]
Hello @rgstephens,

Thanks for your report. 
We're following semver and we're releasing a new version with each PR. 
=> Yes, each major version change, with pattern vX.0.0 is a breaking change.

For instance, [v11.0.0](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/Changelog.md#1100) introduced a breaking change with default values on pod lifecycle. You have the exact diff between v10 and v11 provided in the changelog. 

Does it answer to your need ?
