### ISSUE TITLE
honorLabels and multiple other ServiceMonitor settings are not applied

### ISSUE THREAD

**Issue by aplex** [traefik/traefik-helm-chart#702]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

19.0.3

### What version of Traefik are you using?

-

### What did you do?

Values.yaml has a bunch of ServiceMonitor settings that are not pushed into the ServiceMonitor.yaml.

For example: scrapeInterval,  scrapeTimeout,  honorLabels

### What did you see instead?

-

### What is your environment & configuration?

-

### Additional Information

```shell
https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/servicemonitor.yaml is not using those settings
```

**Comment by mloiseleur** [comment]
Hello @aplex,

Thanks for your report. [This PR](https://github.com/traefik/traefik-helm-chart/pull/703) should fix it. 
Is there any other field you need ?

**Comment by aplex** [comment]
Thanks for the quick fix! I think this set is good for me. 

Just for context, without honorLabels , prometheus-stack changes Traefik metric label "service" to "exported_service", messing up the dashboards that are published in Grafana catalog.
