### ISSUE TITLE
Chart release tags not happening after v19.0.4

### ISSUE THREAD

**Issue by szinn** [traefik/traefik-helm-chart#712]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v19.0.4

### What version of Traefik are you using?

2.9.4

### What did you do?

Upgraded tags to pull a version of the charts after v19.0.4 and pull fails. Going to tags list for the repo shows v19.0.4 as the most recent tag despite new versions, e.g. 20.1.0 being created.

### What did you see instead?

No tagged releases after 19.0.4

### What is your environment & configuration?

N/A

**Comment by charlie-haley** [comment]
Hi @szinn, this has now been fixed as part of https://github.com/traefik/traefik-helm-chart/pull/713, thanks for raising this!
