### ISSUE TITLE
v20.1.1 chart release missing from gh-pages branch / chart repo

### ISSUE THREAD

**Issue by brandond** [traefik/traefik-helm-chart#719]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v20.1.1

### What version of Traefik are you using?

v2.9.4

### What did you do?

Tried to install chart from helm repo.

### What did you see instead?

Chart not available in helm repo or in `gh-pages` branch of this repo. 19.0.4 (without the leading `v`) is the most recent release available for download.

### What is your environment & configuration?

n/a

### Additional Information

```shell
n/a
```

**Comment by mloiseleur** [comment]
Hello @brandond,

Starting with #705 , we are migrating all TraefikLabs Charts to the same Helm Repo.
For Traefik Helm Chart, we are moving from `https://helm.traefik.io/traefik` to `https://traefik.github.io/charts`

Starting with #713, we are also creating GitHub [releases](https://github.com/traefik/traefik-helm-chart/releases).

We tried to make those operations transparent. 

For instance, with Helm CLI on previous Helm repo url, it seems to work:
```bash
$ helm repo add traefik htps://helm.traefik.io/traefik
"traefik" has been added to your repositories
$ helm search repo -l traefik
NAME                	CHART VERSION	APP VERSION	DESCRIPTION                                       
traefik/traefik     	20.1.1       	v2.9.4     	A Traefik based Kubernetes ingress controller     
traefik/traefik     	20.1.0       	2.9.4      	A Traefik based Kubernetes ingress controller     
traefik/traefik     	20.0.0       	2.9.4      	A Traefik based Kubernetes ingress controller     
traefik/traefik     	19.0.4       	2.9.4      	A Traefik based Kubernetes ingress controller     
traefik/traefik     	19.0.3       	2.9.4      	A Traefik based Kubernetes ingress controller     
traefik/traefik     	19.0.2       	2.9.4      	A Traefik based Kubernetes ingress controller     
traefik/traefik     	19.0.1       	2.9.4      	A Traefik based Kubernetes ingress controller     
traefik/traefik     	19.0.0       	2.9.4      	A Traefik based Kubernetes ingress controller     
traefik/traefik     	18.3.0       	2.9.4      	A Traefik based Kubernetes ingress controller     
traefik/traefik     	18.2.0       	2.9.1      	A Traefik based Kubernetes ingress controller     
traefik/traefik     	18.1.0       	2.9.1      	A Traefik based Kubernetes ingress controller     
traefik/traefik     	18.0.0       	2.9.1      	A Traefik based Kubernetes ingress controller     
[...]
``` 

Can you provide more details about your issue of _Chart not available in helm repo_ ?

Can you also detail if/why you need the `gh-pages` branch ?

**Comment by brandond** [comment]
Well, you weren't publishing artifacts, and the old repo at `https://helm.traefik.io/traefik/` started giving us 404s, which broke the K3s CI since we download the chart archive as part of our build process. We looked at the new location referenced from your docs (`https://traefik.github.io/charts`) and that appeared to be coming from the gh-pages branch of this repo, so that's where we pointed. Now things have moved again?

**Comment by mloiseleur** [comment]
Correct and preferred URL is https://traefik.github.io/charts 
It's not coming (only) from this repo, it's coming from all TraefikLabs Helm Charts.

**Comment by brandond** [comment]
Yes, we can update. May I ask why the gh-pages branch was just deleted? That has broken our CI yet again.

**Comment by mloiseleur** [comment]
Cool ! 
The gh-pages branch was deleted in order to be sure that everyone is connected to a maintained Helm repository.
