### ISSUE TITLE
Unable to install traefik over helm due template error

### ISSUE THREAD

**Issue by thehejik** [traefik/traefik-helm-chart#741]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

20.5.2

### What version of Traefik are you using?

v2.9.5

### What did you do?

On deployed k3s:
```
helm repo add traefik https://traefik.github.io/charts
helm repo up
```
and
```
helm upgrade --install traefik traefik/traefik -n traefik --create-namespace --set ports.web.redirectTo=websecure --set ingressClass.enabled=true --set ingressClass.isDefaultClass=true
```

### What did you see instead?

```
Release "traefik" does not exist. Installing it now.
Error: template: traefik/templates/_podtemplate.tpl:206:17: executing "traefik.podTemplate" at <eq .Values.metrics.prometheus.addEntryPointsLabels false>: error calling eq: incompatible types for comparison
```

### What is your environment & configuration?

single node k3s cluster v1.24.6+k3s1 with metrics-server running

### Additional Information

Can be workarounded by adding `--set metrics.prometheus.addEntryPointsLabels=false --set metrics.prometheus.addServicesLabels=false`.

Proposed `--set metrics.prometheus=null` in values.yaml does not help with another error in template:

```
Error: template: traefik/templates/service-metrics.yaml:6:20: executing "traefik/templates/service-metrics.yaml" at <.Values.metrics.prometheus.service>: nil pointer evaluating interface {}.service
```

**Comment by PRBonham** [comment]
I can confirm that the proposed workaround from @thehejik worked for me after getting the exact same error

**Comment by darkweaver87** [comment]
Hello,

Thanks to report this. To make it work, you'll need to upgrade your helm version to at least 3.8.0.

Rémi

**Comment by AllardKrings** [comment]
Thanks a lot for your quick help! Removing the snap-version of helm (3.7) on ubuntu and using the built-in helm version (3.9) of microk8s solved the problem indeed!
