### ISSUE TITLE
Support for Gateway annotations

### ISSUE THREAD

**Issue by mmontes11** [traefik/traefik-helm-chart#752]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

At the moment, I'm disabling the default Gateway being created by the helm chart just because I need to add an extra `cert-manager.io/issuer` annotation to the Gateway, so `cert-manager` is able to [issue a certificate](https://cert-manager.io/docs/usage/gateway/) for it.

It would be ideal to reuse the default Gateway created by this helm chart, but for doing so, the chart should support adding `annotations` in the Gateway object.

PR:
- https://github.com/traefik/traefik-helm-chart/pull/751

**Comment by mloiseleur** [comment]
Thanks for this PR @mmontes11 !

Next release should come this week.

**Comment by mmontes11** [comment]
Thanks @mloiseleur! Will keep an eye on it 👀 and upgrade
