### ISSUE TITLE
Prometheus Set to Null Causes Helm Error

### ISSUE THREAD

**Issue by kylegoch** [traefik/traefik-helm-chart#755]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

20.6.0

### What version of Traefik are you using?

2.9.5

### What did you do?

Already installed helm chart with some custom values and default values. Want to turn off prometheus monitoring since it was defaulted to on.

I set `metrics.prometheus: null` as outlined in the `values.yaml` :
https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L263

### What did you see instead?

I receive this error when doing a helm apply
```
STDERR:
  Error: Failed to render chart: exit status 1: Error: template: traefik/templates/service-metrics.yaml:6:20: executing "traefik/templates/service-metrics.yaml" at <.Values.metrics.prometheus.service>: nil pointer evaluating interface {}.service
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error

COMBINED OUTPUT:
  Error: Failed to render chart: exit status 1: Error: template: traefik/templates/service-metrics.yaml:6:20: executing "traefik/templates/service-metrics.yaml" at <.Values.metrics.prometheus.service>: nil pointer evaluating interface {}.
  ```

This same error message is mentioned in https://github.com/traefik/traefik-helm-chart/issues/741 however the main issue from that issue was resolved updating Helm.

### What is your environment & configuration?

Installed using `helmfile` which is a plugin for helm. Helmfile currently works and updates chart as expected as long as `metrics.prometheus: null` is not set.

Helm v3.10.1
EKS v1.22.15

**Comment by mloiseleur** [comment]
Thanks for your report @kylegoch 
The PR #756 should fix your issue. This PR includes more tests on this use case.
