### ISSUE TITLE
Re-Implement: Allow setting targetPort for https from 1.7

### ISSUE THREAD

**Issue by AceXintense** [traefik/traefik-helm-chart#781]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Please see: https://github.com/helm/charts/issues/885

This ticket was previously implemented into 1.7 but has seemingly been removed in 2.0+ this is currently a requirement for a client cluster as we do not want to manage SSL internally in the cluster.

All that needs to be exposed is the ability to edit the target port as I have to manually change the service each time I helm upgrade and is quite easy to forget which then Traefik serves 404’s as all of the ingress routes are built for HTTP.

If we could get this implemented that would be a massive help as it currently means that our infrastructure as code cannot be completed as there is a manual step. If there is a work around etc I am all ears!

**Comment by carolus-r** [comment]
I am having the same issue as @AceXintense .

**Comment by mloiseleur** [comment]
Hello,

I don't understand why you want to enable `https` on Traefik and not use it. 

If an external network service should provide your SSL termination, then you may enable only `http` on Traefik.
With annotations for this _https LB_ on your `http` service, you will be 100% sure that SSL termination is not done on Traefik.

**Comment by mloiseleur** [comment]
You did not really answer my question. 

When one does not want to use HTTPS on Traefik, then one can just disable it and configure a HTTPS Load-Balancer in front to forward traffic to `http` port on Traefik on a private network. What do you think about this ?

Providing clear traffic on 443/TCP is unexpected, nowadays, to say the least.
