### ISSUE TITLE
Getting Upgrade Failed error: Can't evaluate Helm version with 20.8.0 release.

### ISSUE THREAD

**Issue by sstetlermsft** [traefik/traefik-helm-chart#787]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

20.8.0

### What version of Traefik are you using?

2.9.6

### What did you do?

I'm just trying to deploy this version to a kubernetes cluster and am getting the following error: 

UPGRADE FAILED: template: traefik/templates/deployment.yaml:2:46: executing "traefik/templates/deployment.yaml" at : can't evaluate field HelmVersion in type interface {}

I can see where the helm version check is done in the deployment.yaml.  I'm guessing that that check is failing due to permissions on the agent this is running on, but not sure.

Note that the previous version that installed successfully was: 
- Chart: 20.3.0
- Traefik: 2.9.4

### What did you see instead?

See above.

### What is your environment & configuration?

- Kubernetes 1.24.6

**Comment by sstetlermsft** [comment]
By the way, sorry if this isn't a bug and something that I just missed in the changes.   Also, I have little control over the agent that this is running from, but I think it's: adm-ubuntu-1804-l

Would it be a valid work around to just use the latest helm release before the helm version check (20.5.2) and override the tag in the traefikOverrideValues.yaml?  I'm trying to avoid this mismatch, but at this point, I'm not sure what else to do.  Thanks!

**Comment by mloiseleur** [comment]
What is your helm Version ?

As indicated in the README:
> **Prerequisites**
>  Helm v3 > 3.9.0 [installed](https://helm.sh/docs/using_helm/#installing-helm): helm version

**Comment by sstetlermsft** [comment]
Hi, Thanks for responding.  It was 3.5.8.  Updating to 3.9.1 gave me the same error.

**Comment by sstetlermsft** [comment]
One thing I was curious about is that when we upgrade with a new chart, should we also be updating our traefikOverrideValues.yaml with what's in the values.yaml.  We rarely update our override file, but have in the past due to some defaults that we needed to override.  In those cases, it's always deployed successfully, but didn't function.  I was trying to go back a few versions (before the helm version check) to see if that would deploy and am getting a different error related to checking the prometheus service (traefik/templates/service-metrics.yaml:6:20: executing "traefik/templates/service-metrics.yaml" at : nil pointer evaluating interface {}.service).  I know this is a completely different problem and I should just search for the answer, but it's not clear to me of the best way to upgrade.  It'd definitely help if there were specific callouts for what breaks in each release.  Again, thanks for your help.

**Comment by sstetlermsft** [comment]
I think I might know what's happening.  We don't have complete control of the agents that are running these deployments.  I thought I would be able to configure the agent to run 3.9.1.  I'm thinking this version of helm isn't yet supported on the agent so it's not actually on the agent which is probably why the error is occurring.  I'm running one more test to confirm this theory.  If my theory is correct, at this time the latest version I can use is 3.8.1.  That being said, please don't look into this further until my next comment.

**Comment by sstetlermsft** [comment]
Ok, it took a while since I got distracted, but I confirmed that when I try to deploy with a known available / installed helm version 3.8.1, that I get the proper error message:

- UPGRADE FAILED: execution error at (traefik/templates/deployment.yaml:3:8): ERROR: Helm >= 3.9.0 is required

I think this error I was getting is related to helm not being installed:

- UPGRADE FAILED: template: traefik/templates/deployment.yaml:2:46: executing "traefik/templates/deployment.yaml" at : can't evaluate field HelmVersion in type interface {}

Sorry about wasting your time.  I'll close this out.
