### ISSUE TITLE
Define Multiple Ingress Classes

### ISSUE THREAD

**Issue by jseiser** [traefik/traefik-helm-chart#788]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Since this chart includes CRDS, I would expect to be able to define multiple Ingress Classes, so I do not have to install this chart twice and deal with both attempting to install the same CRDS.

Our situation:

We have public, and private services.  So i need an ingressClass which creates a Public AWS LB, and an ingress class which creates a Private/Internal AWS LB.  A service would never be `both`.

With something like the AWS ALB controller, you define these on the ingress itself, and which the nginx controller chart, you would just install the chart twice, using different ingress CLass names.

With this chart, I would be worried about have 2 charts handling the same CRDS.

**Comment by mloiseleur** [comment]
With [`service.internal`](https://github.com/traefik/traefik-helm-chart/blob/0f51df0eedf774942de93262f4fda579e00b0f98/traefik/values.yaml#L707), you can already provide an internal `Service`
With [`extraObjects`](https://github.com/traefik/traefik-helm-chart/blob/0f51df0eedf774942de93262f4fda579e00b0f98/traefik/values.yaml#L861), you can provide your own additional object, like this additional `IngressClass` specific to your use case.

Would that fit your need ?

**Comment by jseiser** [comment]
I do not think the internal service works

Any example on the extra object stuff?

**Comment by mloiseleur** [comment]
There is an [EXAMPLE](https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md) file on this repo. Some are using extra Object.

**Comment by gregorycuellar** [comment]
I have the same need as @jseiser.

For what I understood, ( and I might be wrong ), the internal service is just mapping the same entrypoints so a service would be accessible on both public and private access.
Also, by creating the second ingress class via extra object, how will it be handled ? It's not clear for me.

Having 2 charts, implies of having 2 separated dashborads, which is not ideal.

In order to separate public and private, the only way I found is to create separated entrypoints ( not exposed ) and create an internal service to target those new ports. @mloiseleur Do you think it's the correct way to proceed ?

Thanks
Have a nice day

**Comment by mloiseleur** [comment]
@gregorycuellar There's no _correct_ way. It depends of your needs.

* A `ClusterIP` Service is already limited to [Kubernetes private network](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types).
* One can enforce isolation using entryPoints for your IngressRoute. 
* One can also enforce it with middlewares like [IPWhiteList](https://doc.traefik.io/traefik/middlewares/http/ipwhitelist/).

And there are probably other ways :)

**Comment by jseiser** [comment]
@mloiseleur 

Wanted to report back, we have not been able to find a way to implement this.  The internal service is definitely not a viable solution.  The extraObject stuff sounds like it would work but after a few failed attempts we had to just go back to nginx to keep traffic moving.

I will go a head and close though, since I believe you that there is probably a way to make this work if you understand what you are doing.

Thank you.
