### ISSUE TITLE
Chart installation failed on latest k8s version

### ISSUE THREAD

**Issue by furynick** [traefik/traefik-helm-chart#800]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

21.1.0

### What version of Traefik are you using?

v2.9.7

### What did you do?

```
helm install \
  --namespace traefik \
  --create-namespace \
  --set service.externalIPs=x.x.x.x \
  --set ingressRoute.dashboard.enabled=false \
  --set autoscaling.enabled=true \
  --set autoscaling.maxReplicas=4 \
  --set autoscaling.minReplicas=2 \
  --set hostNetwork=true \
  --set podSecurityPolicy.enabled=true \
  --set securityContext.runAsNonRoot=false \
  --set logs.general.format=json \
  --set logs.access.enabled=true \
  --set ports.traefik.exposedPort=8080 \
  --set ports.web.exposedPort=80 \
  --set ports.websecure.exposedPort=443 \
  --set ports.amqp-pf.port=56720 \
  --set ports.amqp-pf.exposedPort=5672 \
  --set ports.amqp-pf.protocol=TCP \
  --set ports.amqp-fmk.port=56721 \
  --set ports.amqp-fmk.exposedPort=56721 \
  --set ports.amqp-fmk.protocol=TCP \
  --set ports.amqp-app1.port=56722 \
  --set ports.amqp-app1.exposedPort=56722 \
  --set ports.amqp-app1.protocol=TCP \
  --set ports.amqp-app2.port=56723 \
  --set ports.amqp-app2.exposedPort=56723 \
  --set ports.amqp-app2.protocol=TCP \
  --set ports.memcache-pf.port=11210 \
  --set ports.memcache-pf.exposedPort=11210 \
  --set ports.memcache-pf.protocol=TCP \
  --set ports.memcache-fmk.port=11211 \
  --set ports.memcache-fmk.exposedPort=11211 \
  --set ports.memcache-fmk.protocol=TCP \
  --set ports.memcache-app1.port=11212 \
  --set ports.memcache-app1.exposedPort=11212 \
  --set ports.memcache-app1.protocol=TCP \
  --set ports.memcache-app2.port=11213 \
  --set ports.memcache-app2.exposedPort=11213 \
  --set ports.memcache-app2.protocol=TCP \
  --set ports.metrics.port=9191 \
  --set nodeSelector.vlan=front \
  traefik traefik/traefik
```

### What did you see instead?

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "traefik" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first

### What is your environment & configuration?

```
# kc version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.1
```

**Comment by mloiseleur** [comment]
I'm not sure to understand why you are enabling PodSecurityPolicy on a k8s cluster which [does not support it](https://kubernetes.io/docs/concepts/security/pod-security-policy/).
> `  --set podSecurityPolicy.enabled=true \`

You should be able to install by removing this line.
Does it works for you ?

**Comment by furynick** [comment]
Thanks for pointing me this deprecation, all is fine without PodSecurityPolicy.
