### ISSUE TITLE
Release for traefik 2.9.8 in not built

### ISSUE THREAD

**Issue by devaquila** [traefik/traefik-helm-chart#804]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

21.1.0

### What version of Traefik are you using?

21.1.0

### What did you do?

The new release for traefik 2.9.8 is not created

0s
Run TAG_EXISTS=true
  TAG_EXISTS=true
  if ! [ $(git tag -l "v21.1.0") ]; then
      TAG_EXISTS=false
  fi
  echo TAG_EXISTS=$TAG_EXISTS >> $GITHUB_OUTPUT
  shell: /usr/bin/bash -e {0}
  env:
    tag_prefix: v

### What did you see instead?

The latest version is 21.1.0 for 2.9.7

### What is your environment & configuration?

Oracle linux

**Comment by project0** [comment]
Looks like there is a bug with renovate not updating the default value.yaml as well: https://github.com/traefik/traefik-helm-chart/commit/6c6de90e7fa31875fc317f5bfc58f65aaf490f31

**Comment by mloiseleur** [comment]
It's available. Thanks @devaquila for taking the time to submit a PR !
