### ISSUE TITLE
Add variable `commonLabels` to forward custom labels to all created resources

### ISSUE THREAD

**Issue by alemuro** [traefik/traefik-helm-chart#839]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello! 👋 

For monitoring purposes, I need to add labels to all Kubernetes resources deployed by the chart. This means adding some labels to the Deployment, Pods, Service, HPA, Ingress, and so on. Some of these resources have a variable in the chart called `labels`, but some others (like HPA) haven't.

Working with other charts, I realised that some of them have a variable called `commonLabels` or `extraLabels` (check [Datadog chart](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml#L18), or [Grafana chart](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L140)), which forwards a set of labels to all resources. Would it be possible to integrate this feature? 

I think this new variable can be integrated in the `traefik.labels` helper variable, which is used everywhere. What do you think?
https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/_helpers.tpl#L57-L61

If the change looks good to you I would like to open the PR by myself 😄 So I can contribute to this project

Thanks!
Regards,

**Comment by mloiseleur** [comment]
Hello @alemuro ,

Thanks for your suggestion, it makes a lot of sense. This PR would be more than welcome !

Please check out the [contributor docs] (https://github.com/traefik/traefik-helm-chart/blob/master/CONTRIBUTING.md) and link the PR to this issue.
