### ISSUE TITLE
CRD ingressroutes.traefik.containo.us deprecation

### ISSUE THREAD

**Issue by HannesHil** [traefik/traefik-helm-chart#845]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v23.0.1

### What version of Traefik are you using?

3

### What did you do?

Updating to the latest helm chart version and executing the CRD migration command.

### What did you see instead?

The new and the old traefik CRDs are added via the migration command. Both CRD API versions seem to be respected by the traefik controller. 

But i could not find any information when the  traefik.containo.us/v1alpha1 CRDs will be removed for good from the helm chart. 

### What is your environment & configuration?

helm & kubectl

**Comment by mloiseleur** [comment]
Hello @HannesHil,

Thanks for your interest in Traefik. 
It's explained in the documentation, in the [migration part](https://doc.traefik.io/traefik/migration/v2/#kubernetes-crds).

Does it answer your question ?
