### ISSUE TITLE
Not customisable IngressClass name

### ISSUE THREAD

**Issue by kochetov-dmitrij** [traefik/traefik-helm-chart#855]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

23.0.1

### What version of Traefik are you using?

v2.10.1

### What did you do?

I expected that `providers.kubernetesIngress.ingressClass` is used to set the IngressClass name.

### What did you see instead?

But apparently the release name is used instead:
https://github.com/traefik/traefik-helm-chart/blob/1f29975682db2da0737e85182cda9592e3dd707c/traefik/templates/ingressclass.yaml#L12-L18

The value is referenced only here:
https://github.com/traefik/traefik-helm-chart/blob/1f29975682db2da0737e85182cda9592e3dd707c/traefik/templates/_podtemplate.tpl#L505-L506

Is this a bug?

### What is your environment & configuration?

YAML

**Comment by mloiseleur** [comment]
Hello @kochetov-dmitrij,

Thanks for this report ! It's weird it has not been detected before, but it seems you are right.
Do you think you can submit a PR to fix it ?

**Comment by mloiseleur** [comment]
It's now possible in v23.2.0
