### ISSUE TITLE
Release v2.10.3?

### ISSUE THREAD

**Issue by harryzcy** [traefik/traefik-helm-chart#868]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Update to [traefik v2.10.3](https://github.com/traefik/traefik/releases/tag/v2.10.3)

**Comment by ldez** [comment]
#865

**Comment by harryzcy** [comment]
@ldez thanks
