### ISSUE TITLE
support for dynamic configuration

### ISSUE THREAD

**Issue by wibed** [traefik/traefik-helm-chart#902]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

latest

### What version of Traefik are you using?

latest

### What did you do?

try add custom tls certificates.

```   dynamic.yaml
    tls:
      stores:
        default:
          defaultCertificate:
            certFile: '/certs/tls.crt'
            keyFile: '/certs/tls.key'
```

            

### What did you see instead?

no values, had to resort to a configmap

### What is your environment & configuration?

any

### Additional Information

```shell
none
```

**Comment by mloiseleur** [comment]
did you tried as documented [here](https://github.com/traefik/traefik-helm-chart/blob/571b36aeaf3f6b136f0b3c210a29e3c8d5661acd/traefik/values.yaml#L705) ?

**Comment by wibed** [comment]
i see this as duplicate and would like to mention this thread here.
for any one stumbling upon this

https://github.com/traefik/traefik-helm-chart/issues/187
