### ISSUE TITLE
Traefik V3 new or modified Middlewares not supported

### ISSUE THREAD

**Issue by gcaracuel** [traefik/traefik-helm-chart#911]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

24.0.0

### What version of Traefik are you using?

v3.0

### What did you do?

Migrated ipWhitelist Middleware to ipAllowList but `ipAllowList` is not supported at CRDs.

Similar issues will happen to new Middlewares like `grpcWeb `

### What did you see instead?

When using old type ipWhitelist controller fails, when trying to use ipAllowList CRDs do not allow it.

### What is your environment & configuration?

Not needed

**Comment by gcaracuel** [comment]
Hello @mloiseleur 

Thanks for your reply. I am afraid I won't be able to apply that branch as I am using GitOps approach and this Helm Chart so it would be overwritten. So I could just discard usage of V3 until all this is king of sorted out. 
A new groupversion and keep it aligned in this Helm Chart would have solved this and will add users to V3 beta but I could understand why is not done.

Gonna close this and wait for a stable V3

**Comment by sjmiller609** [comment]
To clarify for anyone else that ends up here - Traefik version 2 and Traefik version 3 have different API specifications for the API version `traefik.io/v1alpha1`. More info here https://github.com/traefik/traefik/pull/9600#issuecomment-1753313008
