### ISSUE TITLE
Internal service is targeting wrong ports

### ISSUE THREAD

**Issue by Aetf** [traefik/traefik-helm-chart#924]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

24.0.0

### What version of Traefik are you using?

2.10.4

### What did you do?

Deploy the helm chart with values including
```
service: {
    type: "ClusterIP",
    externalIPs: [xxx, xxx],
    // an additional internal service for traefik dashbaord
    internal: {
        type: "ClusterIP",
    }
},
ports: {
    web: {
        exposedPort: 80,
        // permanent redirection by default
        redirectTo: "websecure"
    },
    websecure: {
        exposedPort: 443,
        tls: {
            enabled: true
        }
    }
}
```

This creates a `traefik-internal` service along with ingress route for traefik's internal dashboard on entrypoint `traefik`.

And the dashbaord can be accessed via `kubectl port-forward service/traefik-internal 9000:9000`.

### What did you see instead?

Instead of targeting deployment's `traefik` port/entrypoint, the `traefik-internal` service targets exposed ports only (`web` and `websecure`).

This makes the service useless because the only point to have a separate "internal" service is to target otherwise not exposed port/entrypoint (the `traefik` entrypoint).

### What is your environment & configuration?

k3s

**Comment by mloiseleur** [comment]
Hello @Aetf ,

Thanks for your interest in Traefik.

The internal service has been added in order to allow some Ingress to be accessible only from internal IPs, see #436 for more details.

For exposing the traefik dashboard, one can use `websecure` endpoint, see [this EXAMPLE](https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#publish-and-protect-traefik-dashboard-with-basic-auth) for more details.

Does that answer your need ?

**Comment by Aetf** [comment]
Hi @mloiseleur , thanks for reply. Seems like I misunderstood the intended usage of the internal service.

I don't want to expose the traefik dashbaord to the outside (like everything else behind the `websecure` endpoint). I just want something to `port-forward` for debug. I ended up directly port forward the pod, so the service isn't really needed.
