### ISSUE TITLE
missing a parameter about caFiles in clientAuth when I want to configure mtls

### ISSUE THREAD

**Issue by mingmingshiliyu** [traefik/traefik-helm-chart#928]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

latest

### What version of Traefik are you using?

latest

### What did you do?

I want to configure mtls in traefik,
<img width="782" alt="image" src="https://github.com/traefik/traefik-helm-chart/assets/143821597/d9074733-20c9-4b15-a3a1-f28b04245f0d">
but  as is shown in pic,i need a parameter about caFiles,and no caFiles in helm charts 
<img width="584" alt="image" src="https://github.com/traefik/traefik-helm-chart/assets/143821597/0e805e88-8bdf-462f-b4db-9ae26dc1d0e8">

### What did you see instead?

mtls not work

### What is your environment & configuration?

normal

### Additional Information

```shell
none
```

**Comment by mloiseleur** [comment]
I understand that [documentation says that on Kubernetes](https://doc.traefik.io/traefik/https/tls/#client-authentication-mtls), ca should be passed through `secretNames`:

![image](https://github.com/traefik/traefik-helm-chart/assets/97035654/ed7c1d34-5b5f-4679-81ec-2dda8abc9fbb)

Does that answer your question ?

**Comment by mingmingshiliyu** [comment]
> I understand from [documentation on Kubernetes](https://doc.traefik.io/traefik/https/tls/#client-authentication-mtls) that ca should be passed through `secretNames`:
> 
> ![image](https://user-images.githubusercontent.com/97035654/276611716-ed7c1d34-5b5f-4679-81ec-2dda8abc9fbb.png)
> 
> Does that answer your question ?

yes,i created two secret storing ca and client certs,it worked.and next step i want to explore cert management.

**Comment by mloiseleur** [comment]
This repository is dedicated on issues for Traefik Proxy Helm Chart. 
I invite you to share your questions on Traefik Proxy configuration on [community forum](https://community.traefik.io/).
