### ISSUE TITLE
Not able to install latest version (v25.0.0)

### ISSUE THREAD

**Issue by ndeitch** [traefik/traefik-helm-chart#946]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

25.0.0

### What version of Traefik are you using?

24.0.0

### What did you do?

Updating and installing helm chart

```sh
helm repo add traefik https://traefik.github.io/charts
helm repo update
helm install traefik traefik/traefik --namespace=dev
```

### What did you see instead?

Helm repo update fails with following message:

```sh
...Unable to get an update from the "traefik" chart repository (https://traefik.github.io/charts):
	Get "https://traefik.github.io/charts/index.yaml": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Also, it's not possible to load template and default values from [artifacthub.io](https://artifacthub.io/packages/helm/traefik/traefik)

### What is your environment & configuration?

- SO: ubuntu

**Comment by ndeitch** [comment]
It seems that the tar file was not pushed to gh-pages.

**Comment by ndeitch** [comment]
Not even older versions are working, the issue is related to this url: https://traefik.github.io/charts/traefik/traefik-24.0.0.tgz

**Comment by mloiseleur** [comment]
Was it temporary or linked to your network ?
I've made different tests from US and EU, and it seems to works as expected from both area.

**Comment by ndeitch** [comment]
Not sure what happened, I was trying to access from my personal computer in Brazil. It's working now, prob something with network tho.

Thanks @mloiseleur!
