### ISSUE TITLE
Provide OCI Artifact chart release

### ISSUE THREAD

**Issue by endersonmaia** [traefik/traefik-helm-chart#962]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It would be nice to have a OCI Artifact release for the helm charts.

It could be provided via Docker Hub, GitHub Continer Registry, or any other OCI Artifact compatible registry.

```
helm install traefik oci://docker.io/traefik/traefik-chart
```

See: https://helm.sh/docs/topics/registries/

**Comment by mloiseleur** [comment]
That's right. It would be nice :).

**Comment by x0ddf** [comment]
@mloiseleur, as for today, does this [`CHARTS_TOKEN`](https://github.com/traefik/traefik-helm-chart/blob/master/.github/workflows/release.yml#L77) have permission to create a package in the ghcr?

**Comment by darkweaver87** [comment]
@x0ddf and @endersonmaia, you can now install traefik with the command:

```bash
helm install traefik oci://ghcr.io/traefik/helm/traefik
```

Does it solve you issue or you need extra things ?

**Comment by nlamirault** [comment]
works fine @darkweaver87 . You could close i think
