### ISSUE TITLE
service "internal" should expose all ports

### ISSUE THREAD

**Issue by ebuildy** [traefik/traefik-helm-chart#966]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

25.0.0

### What version of Traefik are you using?

2.10.5

### What did you do?

Deploy a Helm release with service internal enabled

### What did you see instead?

service internal is created, but traefik internal port 9000 is missing / not exposed

### What is your environment & configuration?

```
service:
  internal:
    type: clusterIP
```

### Additional Information

```shell
internal service should expose all ports

public service is OK
```

**Comment by mloiseleur** [comment]
In [traefik doc](https://doc.traefik.io/traefik/operations/api/#security), it says:
> Enabling the API in production is not recommended, because it will expose all configuration elements, including sensitive data.

@ebuildy It's not exposed on purpose, for security reason.

**Comment by ebuildy** [comment]
> In [traefik doc](https://doc.traefik.io/traefik/operations/api/#security), it says:
> 
> > Enabling the API in production is not recommended, because it will expose all configuration elements, including sensitive data.
> 
> @ebuildy It's not exposed on purpose, for security reason.

100% agree, I am not talking about exposing the port through an ingress (aka the Service "public") but through the internal service (I think it's made for that). Btw the port is already exposed through the pod, so already available from any kubernetes cluster pod.

Our use case

We run 2 traefik ingress instances (1 for our public traffic / public LB, 1 for our private traffic / private LB). We want to expose "private traefik" dashboard through "public traefik".

**Comment by mloiseleur** [comment]
This helm chart handles only _one_ instance of Traefik. The _internal_ `Service` is when you use the same Traefik for both internal and external traffic.

> We run 2 traefik ingress instances (1 for our public traffic / public LB, 1 for our private traffic / private LB). We want to expose "private traefik" dashboard through "public traefik".

On this kind of setup, would it make sense for you to:

1. On private traefik: exposing a private secured URL with the dashboard
2. On public traefik: expose this private URL

It would follow [separations of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) and allows to secure the whole chain.

**Comment by ebuildy** [comment]
> This helm chart handles only _one_ instance of Traefik. The _internal_ `Service` is when you use the same Traefik for both internal and external traffic.
> 
> > We run 2 traefik ingress instances (1 for our public traffic / public LB, 1 for our private traffic / private LB). We want to expose "private traefik" dashboard through "public traefik".
> 
> On this kind of setup, would it make sense for you to:
> 
> 1. On private traefik: exposing a private secured URL with the dashboard
> 2. On public traefik: expose this private URL
> 
> It would follow [separations of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) and allows to secure the whole chain.

Thanks you, didnt catch well the meaning of "internal" ^^ 

I have created a Service "traefik_api" just to expose the Traefik API, and an Ingress (of course secured by "WhitelistIP" + "forwarded auth").
