### ISSUE TITLE
Support Helm `tpl` function  for `deployment.podAnnotations` 

### ISSUE THREAD

**Issue by ivankatliarchuk** [traefik/traefik-helm-chart#971]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It would be extremely nice to have an option to configure and organize `deployment.podAnnotations` values slightly better.

Example, instead of

```
deployment:
 podAnnotations:
  ad.datadoghq.com/traefik-dev-v1.logs: [{.......}]
```

We could have reference another value or a helper function.
```
deployment:
 podAnnotations:
  ad.datadoghq.com/{{ template "traefik.fullname" . }}.logs: [{.....}]
```

The very same problem is already resolved for `deployment.affinity` values https://github.com/traefik/traefik-helm-chart/blob/9c83a2a8f1533d2122593065818b2dd818a21473/traefik/values.yaml#L912

**Comment by mloiseleur** [comment]
Thanks for this issue @ivankatliarchuk 
Yes, it can be helpful.

Feel free to open a PR about it.
