### ISSUE TITLE
File provider not working

### ISSUE THREAD

**Issue by 5olu7ion** [traefik/traefik-helm-chart#976]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

25.0.0

### What version of Traefik are you using?

2.10.5

### What did you do?

Hello,
first of all: thank you for creating traefik, I really love it :-)
I'm currently trying to rollout traefik via helm in my k8s environment.
Unfortunately I can't get the file provider working. Helm won't create the configmap, and it won't add the cmd args in the deployment.
My helm template test also fails: 
```
[kube:~] 1 $ helm template traefik traefik/traefik --set providers.kubernetesCRD.enabled=false | grep "providers.kubernetescrd"
[kube:~] 1 $ helm template traefik traefik/traefik --set providers.kubernetesCRD.enabled=true | grep "providers.kubernetescrd"
          - "--providers.kubernetescrd"
[kube:~] $ helm template traefik traefik/traefik --set providers.file.enabled=true | grep "providers.file"
[kube:~] 1 $ helm template traefik traefik/traefik --set providers.file.enabled=true --set providers.file.watch=true | grep "providers.file"
[kube:~] 1 $ helm template traefik traefik/traefik --set providers.file.enabled=true --set providers.file.watch=false | grep "providers.file"
[kube:~] 1 $
```

### What did you see instead?

By looking at the chart, I can't see whats going wrong here, because it works nearly the same with the kubernetesCRD Provider:

https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/_podtemplate.tpl#L577  
```
          {{- with .Values.providers.file }}
          {{- if .enabled }}
```
https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/_podtemplate.tpl#L527
```       {{- if .Values.providers.kubernetesCRD.enabled }}```

I saw, that your test in the Build pass perfectly fine, so there must be a stupid mistake on my end:
Tests: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/tests/provider-file_test.yaml#L7
Build: https://github.com/traefik/traefik-helm-chart/actions/runs/7088695073/job/19291744215#step:6:45

### What is your environment & configuration?

K8s with talos, on arch Linux with helm version:
```version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}```

### Additional Information

```shell
I currently use a workaround, which (of course) works well:

additionalArguments:
  - "--providers.file.filename=/data/dynamic.yml"
```
```

**Comment by mloiseleur** [comment]
That's expected, this feature was not yet released.
It's working now, with v26 of this Chart:

```shell
helm repo update
helm search repo traefik/traefik
helm template test --set providers.file.enabled=true traefik/traefik | grep providers.file
          - "--providers.file.directory=/etc/traefik/dynamic"
          - "--providers.file.watch=true"
```
