### ISSUE TITLE
How to assign default CRD group

### ISSUE THREAD

**Issue by LiDaiyan** [traefik/traefik-helm-chart#995]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

26.0.0

### What version of Traefik are you using?

v2.10.0

### What did you do?

helm pull & helm install

### What did you see instead?

when i create ingressroute and kubectl apply, it show configued but it is nothing after kubectl get ingressroute.
I found the reason. There are two groups of CRD containo.us and traefik.io. The default ingressroute is in the containo.us group, and so as other CRD just like middleware...

### What is your environment & configuration?

k3s cluster

### Additional Information

```shell
i ganna say, how to set default group of the CRD? I can delete all the containo.us CRD yaml in the helm chart but it may be not the right way.

thank you very mush, love your contribution, it is very good and useful software.
```

**Comment by mloiseleur** [comment]
Hello @LiDaiyan ,

AFAIK, during the transition between the two groups, you cannot. Traefik v2 won't start without both CRDs group present. 

This should be fixed with Traefik v3, where there should be only one CRD Group.

**Comment by LiDaiyan** [comment]
I get it. Maybe using the elder version is a good solution? thanks.

**Comment by mloiseleur** [comment]
It's up to you. It work with complete API Group:

```shell
kubectl get ingressroute.traefik.io -A
```

What I can say is that, as an Ingress, Traefik is the door to a cluster.
=> It's clearly better to be up-to-date, without known CVEs.

**Comment by LiDaiyan** [comment]
I understand, thank you!
